Board.h
using json = nlohmann::json
PossibleFields
A variant type representing different types of fields on the monopoly board.
std::map<StreetTiers, unsigned int> jsonToStreetRent(const json &element)
Converts JSON data to a map of rent values for street properties.
element The JSON data containing rent values. A map of rent values for street properties.
References FOUR_HOUSES, HOTEL, NO_HOUSES, ONE_HOUSE, THREE_HOUSES, TWO_HOUESES.
Referenced by Board::Board.
std::map<StationTiers, unsigned int> jsonToStationRent(const json &element)
Converts JSON data to a map of rent values for station properties.
element The JSON data containing rent values. A map of rent values for station properties.
References FOUR_STATIONS, ONE_STATION, THREE_STATIONS, TWO_STATIONS.
Referenced by Board::Board.
std::map<UtilityTiers, unsigned int> jsonToUtilityRent(const json &element)
Converts JSON data to a map of rent multipliers for utility properties.
element The JSON data containing rent multipliers. A map of rent multipliers for utility properties.
References ONE_UTILITY, TWO_UTILITIES.
Referenced by Board::Board.