ChanceCard
unsigned int ChanceCard::id_
Unique identifier for the chance card.
ChanceType ChanceCard::type_
Type of the chance card.
int ChanceCard::value_
Value associated with the chance card.
sf::String ChanceCard::text_
Text describing the action of the chance card.
std::string ChanceCard::graphic_path_
Path to the graphic associated with the chance card.
unsigned int ChanceCard::width_
Width of the graphic.
unsigned int ChanceCard::height_
Height of the graphic.
sf::Texture ChanceCard::texture_
Texture for the graphic.
sf::Sprite ChanceCard::sprite_
Sprite for the graphic.
sf::Vector2f ChanceCard::position_
Position of the chance card on the screen.
float ChanceCard::rotation_
Rotation of the chance card graphic.
ChanceCard::ChanceCard(const unsigned int id, const ChanceType type, unsigned int value, const sf::String text, const std::string graphic_path, const unsigned int width, const unsigned int height, const sf::Vector2f position)
Constructor for the ChanceCard class.
id Unique identifier for the chance card. type Type of the chance card. value Value associated with the chance card. text Text describing the action of the chance card. graphic_path Path to the graphic associated with the chance card. width Width of the graphic. height Height of the graphic. position Position of the chance card on the screen.
unsigned int ChanceCard::getId()
Getter for the unique identifier of the chance card.
unsigned int Unique identifier for the chance card.
ChanceType ChanceCard::getType()
Getter for the type of the chance card.
ChanceType Type of the chance card.
Referenced by MonopolyGameEngine::monopolyGameWorker.
int ChanceCard::getValue()
Getter for the value associated with the chance card.
int Value associated with the chance card.
Referenced by MonopolyGameEngine::monopolyGameWorker.
const sf::String ChanceCard::getText()
Getter for the text describing the action of the chance card.
const sf::String& Text describing the action of the chance card.
Referenced by MonopolyGameEngine::monopolyGameWorker.
unsigned int ChanceCard::getWidth()
Getter for the width of the graphic associated with the chance card.
unsigned int Width of the graphic.
unsigned int ChanceCard::getHeight()
Getter for the height of the graphic associated with the chance card.
unsigned int Height of the graphic.
const std::string ChanceCard::getGraphicPath()
Getter for the path to the graphic associated with the chance card.
const std::string& Path to the graphic.
float ChanceCard::getRotation()
Getter for the rotation of the chance card graphic.
float Rotation of the chance card graphic.
const sf::Sprite & ChanceCard::getSprite()
Getter for the sprite associated with the chance card graphic.
const sf::Sprite& Sprite of the chance card graphic.
const sf::Texture & ChanceCard::getTexture()
Getter for the texture associated with the chance card graphic.
const sf::Texture& Texture of the chance card graphic.
const sf::Vector2f & ChanceCard::getPosition()
Getter for the position of the chance card on the screen.
const sf::Vector2f& Position of the chance card.
void ChanceCard::setRotation(float new_roation)
Setter for the rotation of the chance card graphic.
new_roation New rotation value.
void ChanceCard::setPosition(sf::Vector2f pos)
Setter for the position of the chance card on the screen.
pos New position value.
void ChanceCard::createSprite()
Creates the sprite for the chance card using its graphic.