Button
sf::RectangleShape Button::buttonShape_
The SFML RectangleShape representing the button.
sf::Text Button::text_
The SFML Text object representing the text on the button.
ScreenEventType Button::type_
The type of screen event associated with the button.
uint Button::btnWidth
The width of the button.
uint Button::btnHeight
The height of the button.
bool Button::isClicked_
Flag indicating if the button is clicked.
bool Button::isVisible_
Flag indicating if the button is visible.
bool Button::isActive_
Flag indicating if the button is active.
bool Button::isFocus_
Flag indicating if the button is in focus.
bool Button::wasReleased_
Flag indicating if the button was released.
sf::Color Button::activeBackColor_
The background color when the button is active.
sf::Color Button::activeTextColor_
The text color when the button is active.
sf::Color Button::inActiveBackColor_
The background color when the button is inactive.
sf::Color Button::inActiveTextColor_
The text color when the button is inactive.
sf::Color Button::focusBackColor_
The background color when the button is in focus.
sf::Color Button::focusTextColor_
The text color when the button is in focus.
Button::Button(ScreenEventType type, sf::String btnText, sf::Vector2f buttonSize, int charSize)
Constructor for the Button class.
type The type of screen event associated with the button. btnText The text displayed on the button. buttonSize The size of the button. charSize The character size of the text.
void Button::draw(sf::RenderWindow &window)
Draws the button on the specified window.
window The SFML window to draw the button on.
bool Button::isMouseOver(sf::RenderWindow &window)
Checks if the mouse is over the button.
window The SFML window. True if the mouse is over the button, false otherwise.
void Button::mouseIsOver()
Virtual function called when the mouse is over the button.
References setButtonFocus.
void Button::mouseIsNotOver()
Virtual function called when the mouse is not over the button.
References setButtonUnfocus.
ScreenEventType Button::getEventType()
Gets the type of screen event associated with the button.
The screen event type.
void Button::setEventType(ScreenEventType event)
Sets the type of screen event associated with the button.
event The screen event type to set.
void Button::setFont(sf::Font &fonts)
Sets the font for the button text.
fonts The font to set.
void Button::setPosition(sf::Vector2f point)
Sets the position of the button.
point The position to set.
void Button::setIsClicked(bool state)
Sets the state of the button as clicked or not clicked.
state The state to set.
bool Button::getIsClicked()
Gets the state of the button (clicked or not clicked).
True if the button is clicked, false otherwise.
sf::Vector2f Button::getSize()
Gets the size of the button.
The size of the button.
void Button::setIsVisible(bool state)
Sets the visibility state of the button.
state The visibility state to set.
bool Button::getIsVisible()
Gets the visibility state of the button.
True if the button is visible, false otherwise.
void Button::setIsActive(bool state)
Sets the active state of the button.
state The active state to set.
bool Button::getIsActive()
Gets the active state of the button.
True if the button is active, false otherwise.
void Button::setIsFocus(bool state)
Sets the focus state of the button.
state The focus state to set.
Referenced by setButtonFocus, setButtonUnfocus.
bool Button::getIsFocus()
Gets the focus state of the button.
True if the button is in focus, false otherwise.
void Button::setWasReleased(bool state)
Sets the state of the button as released or not released.
state The state to set.
bool Button::getWasReleased()
Gets the state of the button (released or not released).
True if the button was released, false otherwise.
sf::Text & Button::getText()
Gets the SFML Text object associated with the button.
The SFML Text object.
void Button::setActiveBackColor(sf::Color color)
Sets the background color and text color when the button is active.
color The background color to set.
void Button::setActiveTextColor(sf::Color color)
Sets the text color when the button is active.
color The text color to set.
void Button::setInactiveBackColor(sf::Color color)
Sets the background color and text color when the button is inactive.
color The background color to set.
void Button::setInactiveTextColor(sf::Color color)
Sets the text color when the button is inactive.
color The text color to set.
void Button::setFocusBackColor(sf::Color color)
Sets the background color and text color when the button is in focus.
color The background color to set.
void Button::setFocusTextColor(sf::Color color)
Sets the text color when the button is in focus.
color The text color to set.
void Button::setButtonFocus()
Sets the button state to focused.
References setIsFocus.
Referenced by mouseIsOver.
void Button::setButtonUnfocus()
Sets the button state to unfocused.
References setIsFocus.
Referenced by mouseIsNotOver.
void Button::updateColors()
Updates the colors of the button based on its state.