Player
bool Player::is_ai_
Indicates whether the player is controlled by AI.
unsigned int Player::ai_level_
AI level of the player. Useless if player is human.
unsigned int Player::id_
Unique identifier for the player.
sf::Color Player::color_
Color associated with the player.
unsigned int Player::position_
Current position of the player on the game board.
std::vector<unsigned int> Player::fields_owned_id_
List of property IDs owned by the player.
unsigned int Player::money_
Amount of money the player has.
unsigned int Player::jail_status_
Jail status of the player.
sf::Texture Player::player_texture_
Texture for the player's sprite.
sf::Sprite Player::player_sprite_
Sprite representing the player on the game board.
float Player::sprite_offset_x_
Offset of the player sprite along the X-axis.
float Player::sprite_offset_y_
Offset of the player sprite along the Y-axis.
unsigned int Player::jail_cards_
Number of jail cards the player has.
unsigned int Player::result_place_
Final result place of the player in the game.
Player::Player()
Default constructor for Player class.
References clearFieldOwnedId, setAiLevel, setId, setIsAi, setJailCards, setJailStatus, setMoney, setPosition, setResultPlace.
Player::Player(unsigned int money)
Constructor for Player class with initial money. money Initial amount of money for the player.
References clearFieldOwnedId, setAiLevel, setId, setIsAi, setJailCards, setJailStatus, setMoney, setPosition, setResultPlace.
unsigned int Player::getPosition() const
Get the current position of the player.
void Player::setPosition(unsigned int new_position)
Set the current position of the player. new_position New position for the player.
Referenced by Player.
bool Player::hasFieldOwnedId(unsigned int id) const
Check if the player owns a property with the specified ID. id ID of the property to check. True if the player owns the property, false otherwise.
Referenced by addFieldOwnedId.
std::vector< unsigned int > Player::getFieldOwnedId() const
Get a vector of property IDs owned by the player.
Referenced by AiPlayer::decideJail, AiPlayer::decideMortgage, AiPlayer::decideUnmortgage.
void Player::addFieldOwnedId(unsigned int id)
Add a property with the specified ID to the list of properties owned by the player. id ID of the property to add.
References hasFieldOwnedId.
void Player::removeFieldOwnedId(unsigned int id)
Remove a property with the specified ID from the list of properties owned by the player. id ID of the property to remove.
void Player::clearFieldOwnedId()
Clear the list of properties owned by the player.
Referenced by Player.
void Player::setMoney(unsigned int value)
Set the amount of money the player has. value New amount of money for the player.
Referenced by Player.
unsigned int Player::getMoney() const
Get the current amount of money the player has.
Referenced by AiPlayer::decideBuildHouse, AiPlayer::decideBuy, AiPlayer::decideJail, decideMortgage, AiPlayer::decideMortgage, decideSellHouse, AiPlayer::decideSellHouse, AiPlayer::decideUnmortgage.
void Player::addMoney(unsigned int value)
Add a specified amount of money to the player's balance. value Amount of money to add.
bool Player::substractMoney(unsigned int value)
Subtract a specified amount of money from the player's balance. value Amount of money to subtract. True if the player had enough money and the subtraction was successful, false otherwise.
void Player::setJailStatus(unsigned int new_jail_status)
Set the jail status of the player. new_jail_status New jail status for the player.
Referenced by Player.
unsigned int Player::getJailStatus() const
Get the current jail status of the player.
void Player::setJailCards(unsigned int new_jail_cards)
Set the number of jail cards the player has. new_jail_cards New number of jail cards for the player.
Referenced by Player.
unsigned int Player::getJailCards() const
Get the current number of jail cards the player has.
void Player::reduceJailStatus()
Reduce the jail status of the player by one.
void Player::setId(unsigned int new_id)
Set the unique identifier for the player. new_id New unique identifier for the player.
References setColor.
Referenced by MonopolyGameEngine::createPlayers, Player.
unsigned int Player::getId() const
Get the unique identifier of the player.
void Player::setColor(sf::Color new_color)
Set the color associated with the player. new_color New color for the player.
Referenced by setId.
sf::Color Player::getColor() const
Get the color associated with the player.
void Player::setIsAi(bool new_is_ai)
Set the AI status of the player. new_is_ai New AI status for the player.
Referenced by AiPlayer::AiPlayer, MonopolyGameEngine::createPlayers, Player, GameEngine::worker.
bool Player::getIsAi() const
Get the AI status of the player.
void Player::setAiLevel(unsigned int ai_level)
Set the AI level of the player. ai_level New AI level for the player.
Referenced by MonopolyGameEngine::createPlayers, Player, GameEngine::worker.
unsigned int Player::getAiLevel() const
Get the AI level of the player.
Referenced by AiPlayer::decideAcceptTrade, AiPlayer::decideAuctionBid, AiPlayer::decideBuildHouse, AiPlayer::decideBuy, AiPlayer::decideJail, AiPlayer::decideOfferTrade, AiPlayer::decideSellHouse.
void Player::setResultPlace(unsigned int place)
Set the final result place of the player in the game.
Referenced by Player.
unsigned int Player::getResultPlace() const
Get the final result place of the player in the game.
void Player::createSprite()
Create the sprite for the player.
sf::Texture & Player::getTexture()
Get the texture of the player's sprite.
sf::Sprite & Player::getSprite()
Get the sprite representing the player on the game board.
float Player::getSpriteOffsetX() const
Get the offset of the player sprite along the X-axis.
float Player::getSpriteOffsetY() const
Get the offset of the player sprite along the Y-axis.
void Player::setSpriteOffsetX(const float offset_x)
Set the offset of the player sprite along the X-axis. offset_x New offset value.
void Player::setSpriteOffsetY(const float offset_y)
Set the offset of the player sprite along the Y-axis. offset_y New offset value.
void Player::setSpritePosition(sf::Vector2f new_pos)
Set the position of the player sprite. new_pos New position for the player sprite.
AiAdapter & Player::getAdapter()
Get the AI adapter (virtual function, needs to be overridden by derived classes). DO NOT USE THIS Reference to the AI adapter.
virtual ann::neuralnet& Player::getNeuralNetwork()
Get the Neural Network of a player (virtual function, needs to be overridden by derived classes). Reference to the neuralnet class from a tinyai library.
BuyDecision Player::decideBuy(unsigned int index)
Make a buying decision (virtual function, needs to be overridden by derived classes). index Index of the property to consider. BuyDecision object representing the decision.
References BUY.
JailDecision Player::decideJail()
Make a jail decision (virtual function, needs to be overridden by derived classes). JailDecision object representing the decision.
References ROLL.
Decision Player::decideMortgage(unsigned int index)
Make a mortgage decision (virtual function, needs to be overridden by derived classes). index Index of the property to consider. Decision object representing the mortgage decision.
References getMoney, NO, YES.
Decision Player::decideUnmortgage(unsigned int index)
Make an unmortgage decision (virtual function, needs to be overridden by derived classes). index Index of the property to consider. Decision object representing the unmortgage decision.
References YES.
unsigned int Player::decideAuctionBid(unsigned int price)
Make a decision for auction bidding (virtual function, needs to be overridden by derived classes). price Current price in the auction. The bid amount decided by the player.
unsigned int Player::decideBuildHouse()
Make a decision for building a house (virtual function, needs to be overridden by derived classes). The index of the property on which to build a house.
unsigned int Player::decideSellHouse()
Make a decision for selling a house (virtual function, needs to be overridden by derived classes). The index of the property from which to sell a house.
References getMoney.
Decision Player::decideOfferTrade()
Make a decision for offering a trade (virtual function, needs to be overridden by derived classes). Decision object representing the trade offer.
References NO.
Decision Player::decideAcceptTrade()
Make a decision for accepting a trade (virtual function, needs to be overridden by derived classes). Decision object representing the acceptance of the trade.
References NO.