ActiveScreen
ContextWindow* ActiveScreen::context_window_
Pointer to the context window.
sf::Font ActiveScreen::font_
The SFML font used for text on the screen.
std::vector<std::shared_ptr<Button> > ActiveScreen::buttons_
Vector of buttons displayed on the screen.
std::vector<std::shared_ptr<sf::Text> > ActiveScreen::texts_
Vector of SFML Text objects displayed on the screen.
ActiveScreenType ActiveScreen::type_
The type of the active screen.
ActiveScreen::ActiveScreen()
Constructor for the ActiveScreen class.
virtual ScreenEventType ActiveScreen::worker()=0
Pure virtual function representing the worker function for the screen.
The ScreenEventType associated with the user interaction.
virtual void ActiveScreen::draw()=0
Pure virtual function to draw the screen.
sf::Font & ActiveScreen::getFont()
Gets the SFML font used for text on the screen.
The SFML font.
Referenced by GameMenuScreen::gameMenuCreate, GameScreen::GameScreen, MainMenuScreen::mainMenuCreate.
void ActiveScreen::setFont(sf::Font font)
Sets the SFML font used for text on the screen.
font The SFML font to set.
Referenced by GameMenuScreen::gameMenuCreate, GameScreen::GameScreen, MainMenuScreen::mainMenuCreate.
void ActiveScreen::addButton(std::shared_ptr< Button > button_tmp)
Adds a button to the screen.
button_tmp The button to add.
Referenced by GameMenuScreen::gameMenuCreate, MainMenuScreen::mainMenuCreate.
void ActiveScreen::addText(std::shared_ptr< sf::Text > text_tmp)
Adds a text object to the screen.
text_tmp The SFML Text object to add.
std::vector< std::shared_ptr< Button > > & ActiveScreen::getButtons()
Gets the vector of buttons displayed on the screen.
Vector of shared pointers to Button objects.
Referenced by GameMenuScreen::draw, MainMenuScreen::draw, GameMenuScreen::gameMenuCreate, MainMenuScreen::mainMenuCreate, GameMenuScreen::setAILevelColumnVisibility, GameMenuScreen::setDefaultAILevelButtonsFocus, GameMenuScreen::setOtherButtonsInactive, GameMenuScreen::worker, MainMenuScreen::worker.
std::vector< std::shared_ptr< sf::Text > > & ActiveScreen::getTexts()
Gets the vector of SFML Text objects displayed on the screen.
Vector of shared pointers to SFML Text objects.
Referenced by GameMenuScreen::draw.
ContextWindow * ActiveScreen::getContextWindow()
Gets the pointer to the ContextWindow.
Pointer to the ContextWindow.
Referenced by GameMenuScreen::draw, MainMenuScreen::draw, GameScreen::draw, GameMenuScreen::gameMenuCreate, MainMenuScreen::mainMenuCreate, GameMenuScreen::worker, MainMenuScreen::worker, GameScreen::worker.
void ActiveScreen::setContextWindow(ContextWindow *)
Sets the pointer to the ContextWindow.
context_window Pointer to the ContextWindow to set.
Referenced by GameMenuScreen::gameMenuCreate, GameScreen::GameScreen, MainMenuScreen::mainMenuCreate.
ActiveScreenType ActiveScreen::getScreenType()
Gets the type of the active screen.
The ActiveScreenType.
void ActiveScreen::setScreenType(ActiveScreenType type)
Sets the type of the active screen.
type The ActiveScreenType to set.
Referenced by GameMenuScreen::GameMenuScreen, GameScreen::GameScreen, MainMenuScreen::MainMenuScreen.
void ActiveScreen::buttonSetColors(std::shared_ptr< Button > buttonPtr)
Sets the colors of a button based on its state.
buttonPtr The shared pointer to the Button.
Referenced by GameMenuScreen::worker, MainMenuScreen::worker, GameScreen::worker.
std::vector< std::shared_ptr< playerSettings > > ActiveScreen::getPlayersSettings() const
Virtual function to get players' settings.
Vector of shared pointers to playerSettings objects.
std::vector< std::shared_ptr< Player > > ActiveScreen::getPlayersResult()
Virtual function to get players' results.
Vector of shared pointers to Player objects.