ann::neuralnet
std::vector<neuron> ann::neuralnet::nodes
bool ann::neuralnet::recurrent
std::vector<size_t> ann::neuralnet::input_nodes
std::vector<size_t> ann::neuralnet::bias_nodes
std::vector<size_t> ann::neuralnet::output_nodes
double ann::neuralnet::sigmoid(double x)
void ann::neuralnet::evaluate_nonrecurrent(const std::vector< double > &input, std::vector< double > &output)
void ann::neuralnet::evaluate_recurrent(const std::vector< double > &input, std::vector< double > &output)
ann::neuralnet::neuralnet()
void ann::neuralnet::from_genome(const neat::genome &a)
References neat::network_info_container::bias_size, neat::genome::genes, ann::neuron::in_nodes, neat::network_info_container::input_size, neat::genome::network_info, neat::network_info_container::output_size, neat::network_info_container::recurrent, ann::neuron::type.
void ann::neuralnet::evaluate(const std::vector< double > &input, std::vector< double > &output)
Referenced by AiPlayer::decideAcceptTrade, AiPlayer::decideAuctionBid, AiPlayer::decideBuildHouse, AiPlayer::decideBuy, AiPlayer::decideJail, AiPlayer::decideMortgage, AiPlayer::decideOfferTrade, AiPlayer::decideSellHouse, AiPlayer::decideUnmortgage.
void ann::neuralnet::import_fromfile(std::string filename)
Referenced by GameEngine::worker.
void ann::neuralnet::export_tofile(std::string filename)