AiAdapter
std::vector<double> AiAdapter::networkInputs_
Vector storing the AI network inputs.
const unsigned int AiAdapter::TURN
Index for turn in network inputs.
const unsigned int AiAdapter::POS
Index for position in network inputs.
const unsigned int AiAdapter::MONEY
Index for money in network inputs.
const unsigned int AiAdapter::CARD
Index for cards in network inputs.
const unsigned int AiAdapter::JAIL
Index for jail state in network inputs.
const unsigned int AiAdapter::OWNER
Index for property ownership in network inputs.
const unsigned int AiAdapter::MORT
Index for mortgage state in network inputs.
const unsigned int AiAdapter::HOUSE
Index for house state in network inputs.
unsigned int AiAdapter::SELECT
Index for selection in network inputs.
const unsigned int AiAdapter::SELECT_MONEY
Index for selection money state in network inputs.
const std::vector<int> AiAdapter::PROPERTIES
Vector representing property states.
const std::vector<int> AiAdapter::HOUSES
Vector representing house states.
AiAdapter::AiAdapter()
Constructor for the AiAdapter class.
std::vector< double > AiAdapter::getInputs()
Gets the AI network inputs.
Vector of AI network inputs.
Referenced by AiPlayer::decideAcceptTrade, AiPlayer::decideAuctionBid, AiPlayer::decideBuildHouse, AiPlayer::decideBuy, AiPlayer::decideJail, AiPlayer::decideMortgage, AiPlayer::decideOfferTrade, AiPlayer::decideSellHouse, AiPlayer::decideUnmortgage.
double AiAdapter::convertMoney(unsigned int money)
Converts money into a format suitable for AI input.
money The money value to convert. The converted money value.
Referenced by setMoney.
double AiAdapter::convertMoneyValue(double value)
Converts money value into a format suitable for AI input.
value The money value to convert. The converted money value.
Referenced by AiPlayer::decideAuctionBid.
double AiAdapter::convertHouseValue(double value)
Converts house value into a format suitable for AI input.
value The house value to convert. The converted house value.
Referenced by AiPlayer::decideBuildHouse, AiPlayer::decideSellHouse.
double AiAdapter::convertPosition(unsigned int position)
Converts position into a format suitable for AI input.
position The position to convert. The converted position.
Referenced by setPosition.
double AiAdapter::convertCard(unsigned int cards)
Converts card value into a format suitable for AI input.
cards The card value to convert. The converted card value.
Referenced by setCard.
double AiAdapter::convertHouse(bool isHotel, unsigned int houseNumber)
Converts house state into a format suitable for AI input.
isHotel Flag indicating if it's a hotel. houseNumber The house number. The converted house state.
Referenced by setHouse.
void AiAdapter::setTurn(unsigned int index)
Sets the turn for a given index.
index The index for which to set the turn.
void AiAdapter::setSelection(unsigned int index)
Sets the selection for a given index.
index The index for which to set the selection.
void AiAdapter::setSelectionState(unsigned int index, int state)
Sets the selection state for a given index.
index The index for which to set the selection state. state The state to set.
void AiAdapter::setMoneyContext(int state)
Sets the money context state.
state The state to set.
void AiAdapter::clearSelectionState()
Clears the selection state.
void AiAdapter::setPosition(unsigned int index, unsigned int position)
Sets the position for a given index.
index The index for which to set the position. position The position to set.
References convertPosition.
void AiAdapter::setMoney(unsigned int index, unsigned int money)
Sets the money for a given index.
index The index for which to set the money. money The money to set.
References convertMoney.
void AiAdapter::setCard(unsigned int index, unsigned int cards)
Sets the card for a given index.
index The index for which to set the card. cards The card to set.
References convertCard.
void AiAdapter::setJail(unsigned int index, unsigned int state)
Sets the jail state for a given index.
index The index for which to set the jail state. state The state to set.
void AiAdapter::setOwner(unsigned int property, unsigned int state)
Sets the owner state for a given property.
property The property for which to set the owner state. state The state to set.
void AiAdapter::setMortgage(unsigned int property, unsigned int state)
Sets the mortgage state for a given property.
property The property for which to set the mortgage state. state The state to set.
void AiAdapter::setHouse(bool isHotel, unsigned int houseNumber, unsigned int id)
Sets the house state for a given house.
isHotel Flag indicating if it's a hotel. houseNumber The house number. id The ID to set.
References convertHouse.