UtilityField
std::map<UtilityTiers, unsigned int> UtilityField::rent_multipliers_
UtilityField::UtilityField(const unsigned int id, const FieldType type, const std::string name, const std::string graphic_path, const unsigned int width, const unsigned int height, const float rotation, const sf::Vector2i position, const unsigned int price, const std::map< UtilityTiers, unsigned int > rent_multipliers, const std::vector< unsigned int > group_members, const unsigned int Mortgage)
Constructor for the UtilityField class.
id The ID of the field. type The type of the field. name The name of the field. graphic_path The file path to the field's graphic. width The width of the field. height The height of the field. rotation The rotation angle of the field. position The position of the field on the board. price The price of the property. rent_multipliers The rent multipliers for different tiers. group_members The IDs of the group members (properties in the same group). mortgage The mortgage value of the property.
const std::map< UtilityTiers, unsigned int > UtilityField::getRentMultipliers()
Calculates the rent for the utility property.
Map for Utility tiers mapped to mulitpliers values
Referenced by MonopolyGameEngine::calculateRent, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int UtilityField::calculateRent(unsigned int dice_roll)
Calculates the rent for the utility property.
dice_roll The roll of the dice. The calculated rent value.