PropertyField
unsigned int PropertyField::price_
std::vector<unsigned int> PropertyField::group_members_
unsigned int PropertyField::mortgage_
bool PropertyField::is_mortgaged_
unsigned int PropertyField::unmortgage_value_
std::shared_ptr<Player> PropertyField::owner_
sf::RectangleShape PropertyField::owner_flag_
PropertyField::PropertyField(const unsigned int id, const FieldType type, const std::string name, const std::string graphic_path, const unsigned int width, const unsigned int height, const float rotation, const sf::Vector2i position, const unsigned int price, const std::vector< unsigned int > group_members, const unsigned int mortgage)
Constructor for the PropertyField class.
id The ID of the field. type The type of the field. name The name of the field. graphic_path The file path to the field's graphic. width The width of the field. height The height of the field. rotation The rotation angle of the field. position The position of the field on the board. price The price of the property. group_members The IDs of the group members (properties in the same group). mortgage The mortgage value of the property.
unsigned int PropertyField::getPrice()
Gets the price of the property.
The price of the property.
Referenced by MonopolyGameEngine::performAuction, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
const std::vector< unsigned int > PropertyField::getGroupMembers()
Gets the IDs of the group members (properties in the same group).
The IDs of the group members.
Referenced by MonopolyGameEngine::calculateGroupFieldsOwned, MonopolyGameEngine::colorGroupEmpty, MonopolyGameEngine::groupCompleted, MonopolyGameEngine::isBuildingLegal, MonopolyGameEngine::isDestroyingLegal, MonopolyGameEngine::isHotelBuildingLegal, MonopolyGameEngine::isHotelDestroyingLegal.
unsigned int PropertyField::getMortgage()
Gets the mortgage value of the property.
The mortgage value of the property.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
bool PropertyField::getIsMortgaged()
Checks if the property is mortgaged.
True if the property is mortgaged, false otherwise.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::calculateRent, GameScreen::draw, MonopolyGameEngine::isBuildingLegal, MonopolyGameEngine::isDestroyingLegal, MonopolyGameEngine::isHotelBuildingLegal, MonopolyGameEngine::isHotelDestroyingLegal.
unsigned int PropertyField::getUnmortgageValue()
Gets the value needed to unmortgage the property.
The value needed to unmortgage the property.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker.
std::shared_ptr< Player > PropertyField::getOwner()
Gets the owner of the property.
A shared pointer to the owner of the property.
Referenced by MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::calculateRent, GameScreen::draw, MonopolyGameEngine::monopolyGameWorker.
sf::RectangleShape & PropertyField::getOwnerFlag()
Gets the owner flag sprite.
The owner flag sprite.
Referenced by GameScreen::draw.
void PropertyField::setIsMortgaged(bool new_state)
Sets the mortgaged state of the property.
new_state The new mortgaged state.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, resetDefault, StreetField::resetDefault.
void PropertyField::setOwner(std::shared_ptr< Player > new_owner)
Sets the owner of the property.
new_owner A shared pointer to the new owner.
Referenced by Withdraw::makeWithdraw.
void PropertyField::resetOwner()
Resets the owner of the property.
Referenced by resetDefault, StreetField::resetDefault.
void PropertyField::resetDefault()
Resets the property to its default state.
References resetOwner, setIsMortgaged.
void PropertyField::createFlagSprite()
Creates the owner flag sprite.
References Field::getHeight, Field::getId, Field::getPosition, Field::getRotation, Field::getWidth.
Referenced by Board::Board.