Withdraw
bool Withdraw::ALLOW_ONE_SIDE_BENEFIT_WITHDRAW
float Withdraw::PROPERTY_SHOW_SCALE
If only one side can benefit from second side.
std::shared_ptr<Board> Withdraw::gameboard_
Scale factor for property sprite display.
const unsigned int Withdraw::FONT_SIZE
Pointer to monopoly gameboard object ,source for data about fields.
sf::Font Withdraw::font_
Font size for rendering text.
std::vector<std::shared_ptr<Button> > Withdraw::buttons_
Font used for rendering text.
std::vector<std::shared_ptr<sf::Text> > Withdraw::texts_
Vector of buttons used in the withdrawal process.
std::shared_ptr<sf::Text> Withdraw::choose_player_text_
Vector of text objects used in the withdrawal process.
sf::Vector2f Withdraw::CHOOSE_PLAYER_TEXT_POSITION
Vector of text objects used in the withdrawal choose player process.
std::shared_ptr<Button> Withdraw::choose_player_1_button_
Origin position for first text object used in the withdrawal choose player process.
std::shared_ptr<Button> Withdraw::choose_player_2_button_
Pointer to button object for choosing withdrawal player.
std::shared_ptr<Button> Withdraw::choose_player_3_button_
Pointer to button object for choosing withdrawal player.
std::shared_ptr<Button> Withdraw::choose_player_4_button_
Pointer to button object for choosing withdrawal player.
sf::Vector2f Withdraw::RESIGN_BUTTON_POSITION
Pointer to button object for choosing withdrawal player.
std::shared_ptr<Button> Withdraw::resign_button_
Origin position for resign button used in the withdrawal choose player process.
sf::Vector2f Withdraw::RESIGN_VALUE_BUTTON_POSITION
Pointer to button object for resigning from choosing withdrawal player.
std::shared_ptr<Button> Withdraw::resign_value_button_
Origin position for resign button used in the withdrawal main process.
std::shared_ptr<Button> Withdraw::submit_value_button_
Pointer to button object for resigning from withdrawal process.
sf::Vector2f Withdraw::COLUMN_1_POSITION
Pointer to button object for submitting withdrawal process.
std::shared_ptr<sf::Text> Withdraw::player_1_text_
Origin position for first column of withdrawal main process.
std::shared_ptr<sf::Text> Withdraw::player_1_money_
Pointer to text object for first withdrawal player name.
unsigned int Withdraw::player_1_money_buffer_
Pointer to text object for first withdrawal player money. Buffer for Player 1's money.
unsigned int Withdraw::player_1_money_index_buffer_
Buffer for Player 1's offered money.
std::vector<unsigned int> Withdraw::player1Properties_
std::shared_ptr<Button> Withdraw::plus_1_player_1_button_
Vector of properties id's of player1.
std::shared_ptr<Button> Withdraw::plus_10_player_1_button_
Pointer to button for add 1 money to offer value from player1.
std::shared_ptr<Button> Withdraw::plus_100_player_1_button_
Pointer to button for add 10 money to offer value from player1.
std::shared_ptr<Button> Withdraw::minus_1_player_1_button_
Pointer to button for add 100 money to offer value from player1.
std::shared_ptr<Button> Withdraw::minus_10_player_1_button_
Pointer to button for substract 1 money from offer value from player1.
std::shared_ptr<Button> Withdraw::minus_100_player_1_button_
Pointer to button for substract 10 money from offer value from player1.
sf::Vector2f Withdraw::PROPERTY_PLAYER1_POSITION
Pointer to button for substract 100 money from offer value from player1.
sf::Sprite Withdraw::property_player_1_sprite_
Origin position for player 1 properties sprite.
std::shared_ptr<sf::Texture> Withdraw::property_player_1_texture_
Player 1 properties sprite.
std::vector<std::shared_ptr<sf::Text> > Withdraw::property_player_1_texts_
Player 1 properties texture.
sf::Vector2f Withdraw::NEXT_PROPERTY_PLAYER1_BUTTON_POSITION
Vector of text objects used in player 1 property description.
sf::Vector2f Withdraw::PREVIOUS_PROPERTY_PLAYER1_BUTTON_POSITION
Origin position for player 1 properties next button.
std::shared_ptr<Button> Withdraw::next_property_player_1_button_
Origin position for player 1 properties previous button.
std::shared_ptr<Button> Withdraw::previous_propertyplayer_1_button_
Pointer to button for player 1 next property showing.
unsigned int Withdraw::current_property_player_1_showed_
Pointer to button for player 1 previous property showing.
sf::Vector2f Withdraw::COLUMN_2_POSITION
Field position of currently showed player 1 property
std::shared_ptr<sf::Text> Withdraw::player_1_index_text_
Origin position for second column of withdrawal main process.
std::shared_ptr<sf::Text> Withdraw::player_1_index_money_
Pointer to text object for player 1 offer name.
std::vector<unsigned int> Withdraw::player_1_index_properties_
Pointer to text object for player 1 offer money.
sf::Vector2f Withdraw::PROPERTY_PLAYER1_INDEX_POSITION
Vector of properties id's of player 1 offer.
sf::Sprite Withdraw::property_player_1_index_sprite_
Origin position for player 1 offered properties sprite.
std::shared_ptr<sf::Texture> Withdraw::property_player_1_index_texture_
Player 1 offered properties sprite.
std::vector<std::shared_ptr<sf::Text> > Withdraw::property_player_1_index_texts_
Player 1 offered propertie texture.
sf::Vector2f Withdraw::NEXT_PROPERTY_PLAYER1_INDEX_BUTTON_POSITION
Vector of text objects used in player 1 offered property description.
sf::Vector2f Withdraw::PREVIOUS_PROPERTY_PLAYER1_INDEX_BUTTON_POSITION
Origin position for player 1 offered properties next button.
std::shared_ptr<Button> Withdraw::next_property_player_1_index_button_
Origin position for player 1 previous properties next button.
std::shared_ptr<Button> Withdraw::previous_property_player_1_index_button_
Pointer to button for player 1 next offered property showing.
unsigned int Withdraw::current_property_player_1_index_showed_
Pointer to button for player 1 previous offered property showing.
sf::Vector2f Withdraw::COLUMN_3_POSITION
Field position of currently showed player 1 offered property
std::shared_ptr<sf::Text> Withdraw::player_2_index_text_
Origin position for third column of withdrawal main process.
std::shared_ptr<sf::Text> Withdraw::player_2_index_money_
Pointer to text object for player 2 offer name.
std::vector<unsigned int> Withdraw::player_2_index_properties_
Pointer to text object for player 2 offer money.
sf::Vector2f Withdraw::PROPERTY_PLAYER2_INDEX_POSITION
Vector of properties id's of player 2 offer.
sf::Sprite Withdraw::property_player_2_index_sprite_
Origin position for player 2 offered properties sprite.
std::shared_ptr<sf::Texture> Withdraw::property_player_2_index_texture_
Player 2 offered properties sprite.
std::vector<std::shared_ptr<sf::Text> > Withdraw::property_player_2_index_texts_
Player 2 offered propertie texture.
sf::Vector2f Withdraw::NEXT_PROPERTY_PLAYER2_INDEX_BUTTON_POSITION
Vector of text objects used in player 2 offered property description.
sf::Vector2f Withdraw::PREVIOUS_PROPERTY_PLAYER2_INDEX_BUTTON_POSITION
Origin position for player 2 offered properties next button.
std::shared_ptr<Button> Withdraw::next_property_player_2_index_button_
Origin position for player 2 previous properties next button.
std::shared_ptr<Button> Withdraw::previousPropertyPlayer2IndexButton_
Pointer to button for player 2 next offered property showing.
unsigned int Withdraw::current_property_player_2_index_showed_
Pointer to button for player 2 previous offered property showing.
sf::Vector2f Withdraw::COLUMN_4_POSITION
Field position of currently showed player 2 offered property
std::shared_ptr<sf::Text> Withdraw::player_2_text_
Origin position for fourth column of withdrawal main process.
std::shared_ptr<sf::Text> Withdraw::player_2_money_
Pointer to text object for second withdrawal player name.
unsigned int Withdraw::player_2_money_buffer_
Pointer to text object for second withdrawal player money. Buffer for Player 2's money.
unsigned int Withdraw::player_2_money_index_buffer_
Buffer for Player 2's offered money.
std::vector<unsigned int> Withdraw::player_2_properties_
std::shared_ptr<Button> Withdraw::plus_1_player_2_button_
Vector of properties id's of player 2.
std::shared_ptr<Button> Withdraw::plus_10_player_2_button_
Pointer to button for add 1 money to offer value from player 2.
std::shared_ptr<Button> Withdraw::plus_100_player_2_button_
Pointer to button for add 10 money to offer value from player 2.
std::shared_ptr<Button> Withdraw::minus_1_player_2_button_
Pointer to button for add 100 money to offer value from player 2.
std::shared_ptr<Button> Withdraw::minus_10_player_2_button_
Pointer to button for substract 1 money from offer value from player 2.
std::shared_ptr<Button> Withdraw::minus_100_player_2_button_
Pointer to button for substract 10 money from offer value from player 2.
sf::Vector2f Withdraw::PROPERTY_PLAYER2_POSITION
Pointer to button for substract 100 money from offer value from player 2.
sf::Sprite Withdraw::property_player_2_sprite_
Origin position for player 1 properties sprite.
std::shared_ptr<sf::Texture> Withdraw::property_player_2_texture_
Player 2 properties sprite.
std::vector<std::shared_ptr<sf::Text> > Withdraw::propertyPlayer2Texts_
Player 2 properties texture.
sf::Vector2f Withdraw::NEXT_PROPERTY_PLAYER2_BUTTON_POSITION
Vector of text objects used in player 1 property description.
sf::Vector2f Withdraw::PREVIOUS_PROPERTY_PLAYER2_BUTTON_POSITION
Origin position for player 2 properties next button.
std::shared_ptr<Button> Withdraw::next_property_player_2_button_
Origin position for player 2 properties previous button.
std::shared_ptr<Button> Withdraw::previous_propertyplayer_2_button_
Pointer to button for player 2 next property showing.
unsigned int Withdraw::current_property_player_2_showed_
Pointer to button for player 2 previous property showing.
sf::Vector2f Withdraw::ADD_PROPERTY_PLAYER1_BUTTON_POSITION
Field position of currently showed player 2 property
sf::Vector2f Withdraw::REMOVE_PROPERTY_PLAYER1_BUTTON_POSITION
Origin position for player 1 add to offered properties button.
std::shared_ptr<Button> Withdraw::add_property_player_1_button_
Origin position for player 1 remove from offered properties button.
std::shared_ptr<Button> Withdraw::remove_property_player_1_button_
Pointer to button for player 1 add to offered properties.
sf::Vector2f Withdraw::ADD_PROPERTY_PLAYER2_BUTTON_POSITION
Pointer to button for player 1 remove from offered properties.
sf::Vector2f Withdraw::REMOVE_PROPERTY_PLAYER2_BUTTON_POSITION
Origin position for player 2 add to offered properties button.
std::shared_ptr<Button> Withdraw::add_property_player_2_button_
Origin position for player 2 remove from offered properties button.
std::shared_ptr<Button> Withdraw::remove_property_player_2_button_
Pointer to button for player 2 add to offered properties.
sf::Vector2f Withdraw::DECISION_TEXT_POSITION
Pointer to button for player 2 remove from offered properties.
std::shared_ptr<sf::Text> Withdraw::player_info_text_
Origin position for player 2 decision stuff.
std::shared_ptr<sf::Text> Withdraw::player_info_money_
Pointer to text object for player 2 name.
std::shared_ptr<sf::Text> Withdraw::player_info_get_properties_
Pointer to text object for player 2 money balance from withdraw.
std::shared_ptr<sf::Text> Withdraw::player_info_lose_properties_
Pointer to text object for player 2 wihdraw properties gain.
sf::Vector2f Withdraw::RESIGN_DECISION_BUTTON_POSITION
Pointer to text object for player 2 wihdraw properties loose.
sf::Vector2f Withdraw::ACCEPT_DECISION_BUTTON_POSITION
Origin position for player 2 accept withdraw button.
std::shared_ptr<Button> Withdraw::resign_decision_button_
Origin position for player 2 resign withdraw button.
std::shared_ptr<Button> Withdraw::accpet_decision_button_
Pointer to button for player 2 resign from withdraw decision.
TurnState Withdraw::turn_state_prev_
Pointer to button for player 2 accept withdraw decision.
std::shared_ptr<Player> Withdraw::player_1_to_with_draw_
Buffer for monopoly engine turn when withdraw was started.
std::shared_ptr<Player> Withdraw::player_2_to_with_draw_
Pointer for player 1 of withdraw (active)
std::shared_ptr< Button > Withdraw::createDefaultButton(sf::String text, unsigned int width, unsigned int height)
Pointer for player 2 of withdraw (passive) Add a button to vector of all buttons for withdraw handling text sf::String object for button text width width of Button object sprite height height of Button object sprite Pointer to created Button object instance
void Withdraw::addButton(std::shared_ptr< Button > button_tmp)
Add a button to vector of all buttons for withdraw handling button_tmp Pointer to Button object
void Withdraw::addText(std::shared_ptr< sf::Text > text_tmp)
Add a text to vector of all texts for withdraw handling text_tmp Pointer to sf::Text object
Withdraw::Withdraw()
Constructor for the Withdraw class.
std::vector< unsigned int > Withdraw::getPlayer1IndexProperties()
Getter for the properties of Player 1 offer.
A vector of unsigned integers representing the indexes of Player 1 offer properties.
std::vector< unsigned int > Withdraw::getPlayer2IndexProperties()
Getter for the properties of Player 2 offer.
A vector of unsigned integers representing the indexes of Player 2 offer properties.
void Withdraw::setPlayer1IndexProperties(std::vector< unsigned int > new_index_properties)
Setter for the properties of Player 1 offer.
new_index_properties A vector of unsigned integers representing the new index for Player 1 offer properties.
void Withdraw::setPlayer2IndexProperties(std::vector< unsigned int > new_index_properties)
Setter for the properties of Player 2 offer.
new_index_properties A vector of unsigned integers representing the new index for Player 2 offer properties.
void Withdraw::setBoard(std::shared_ptr< Board > board_ptr)
Setter for the gameboard.
board_ptr A shared pointer to the Board object.
Referenced by GameScreen::GameScreen.
void Withdraw::setTurnState(TurnState state)
Setter for the turn state of monopolygame when withdraw was started.
state A TurnState enumeration representing the turn state.
TurnState Withdraw::getTurnState()
Getter for the turn state.
The current TurnState enumeration representing the turn state of monopolygame when withdraw was started.
sf::Font & Withdraw::getFont()
Getter for the font used in rendering text.
A reference to the SFML Font object.
Referenced by createChoosePlayerScreen, createDecisionPlayerScreen, createValuePlayerScreen, showProperty.
unsigned int Withdraw::getFontSize() const
Getter for the font size used in rendering text.
An unsigned integer representing the font size.
Referenced by createChoosePlayerScreen, createDecisionPlayerScreen, createValuePlayerScreen, showProperty.
void Withdraw::setFont(sf::Font font)
Setter for the font used in rendering text.
font A reference to the SFML Font object.
Referenced by GameScreen::GameScreen.
std::vector< std::shared_ptr< Button > > & Withdraw::getButtons()
Getter for the vector of buttons used in the withdrawal process.
A vector of shared pointers to Button objects.
Referenced by GameScreen::draw, GameScreen::GameScreen.
std::vector< std::shared_ptr< sf::Text > > & Withdraw::getTexts()
Getter for the vector of text objects used in the withdrawal process.
A vector of shared pointers to SFML Text objects.
Referenced by GameScreen::draw.
std::shared_ptr< Button > Withdraw::getPlayer1Button()
Getter for button for choosing Player 1 as passive in withdraw.
A shared pointer to choose Player 1 Button object.
std::shared_ptr< Button > Withdraw::getPlayer2Button()
Getter for button for choosing Player 2 as passive in withdraw.
A shared pointer to choose Player 2 Button object.
std::shared_ptr< Button > Withdraw::getPlayer3Button()
Getter for button for choosing Player 3 as passive in withdraw.
A shared pointer to choose Player 3 Button object.
std::shared_ptr< Button > Withdraw::getPlayer4Button()
Getter for button for choosing Player 4 as passive in withdraw.
A shared pointer to choose Player 4 Button object.
std::shared_ptr< Button > Withdraw::getResignButton()
Getter for the resign button.
A shared pointer to the resign Button object.
void Withdraw::createChoosePlayerScreen()
Creates the screen for choosing players during withdrawal.
References getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void Withdraw::createValuePlayerScreen()
Creates the screen for specifying values during withdrawal.
References getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void Withdraw::createDecisionPlayerScreen()
Creates the screen for making decisions during withdrawal.
References getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void Withdraw::setChooseScreenVisible(bool is_visible)
Sets the visibility of the choose player screen.
is_visible A boolean indicating whether the screen should be visible.
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::setValueScreenVisible(bool is_visible)
Sets the visibility of the value player screen.
is_visible A boolean indicating whether the screen should be visible.
References showProperty.
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::setDecisionScreenVisible(bool is_visible)
Sets the visibility of the decision player screen.
is_visible A boolean indicating whether the screen should be visible.
References Field::getName.
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::setPlayer1ToWithdraw(std::shared_ptr< Player > player_ptr)
Sets Active Player for withdrawal.
player_ptr A shared pointer to the Player object.
void Withdraw::setPlayer2ToWithdraw(std::shared_ptr< Player > player_ptr)
Sets Passive Player for withdrawal.
player_ptr A shared pointer to the Player object.
Referenced by MonopolyGameEngine::monopolyGameWorker.
std::shared_ptr< Player > Withdraw::getPlayer1ToWithdraw()
Getter for Active Player object.
A shared pointer to the Player object.
std::shared_ptr< Player > Withdraw::getPlayer2ToWithdraw()
Getter for Passive Player object.
A shared pointer to the Player object.
std::shared_ptr< Button > Withdraw::getResignValueButton()
Getter for the resign button from value screen.
A shared pointer to the resign value Button object.
std::shared_ptr< Button > Withdraw::getSubmitValueButton()
Getter for the submit value button from value screen.
A shared pointer to the submit value Button object.
std::shared_ptr< Button > Withdraw::getPlayer1minus1()
Getter for Active Player minus 1 money button.
A shared pointer to the minus 1 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer1minus10()
Getter for Active Player minus 10 money button.
A shared pointer to the minus 10 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer1minus100()
Getter for Active Player minus 100 money button.
A shared pointer to the minus 100 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer1plus1()
Getter for Active Player plus 1 money button.
A shared pointer to the minus 1 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer1plus10()
Getter for Active Player plus 10 money button.
A shared pointer to the minus 10 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer1plus100()
Getter for Active Player plus 100 money button.
A shared pointer to the minus 100 Button object for Active Player.
std::shared_ptr< Button > Withdraw::getPlayer2minus1()
Getter for Passive Player minus 1 money button.
A shared pointer to the minus 1 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer2minus10()
Getter for Passive Player minus 10 money button.
A shared pointer to the minus 10 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer2minus100()
Getter for Passive Player minus 100 money button.
A shared pointer to the minus 100 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer2plus1()
Getter for Passive Player plus 1 money button.
A shared pointer to the plus 1 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer2plus10()
Getter for Passive Player plus 10 money button.
A shared pointer to the plus 10 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer2plus100()
Getter for Passive Player plus 100 money button.
A shared pointer to the plus 100 Button object for Passive Player.
std::shared_ptr< Button > Withdraw::getPlayer1NextButton()
Getter for Player 1 next property button.
A shared pointer to the next property Button object for Player 1.
std::shared_ptr< Button > Withdraw::getPlayer1PreviousButton()
Getter for Player 1 previous property button.
A shared pointer to the previous property Button object for Player 1.
std::shared_ptr< Button > Withdraw::getPlayer2NextButton()
Getter for Player 2 next property button.
A shared pointer to the next property Button object for Player 2.
std::shared_ptr< Button > Withdraw::getPlayer2PreviousButton()
Getter for Player 2 previous property button.
A shared pointer to the previous property Button object for Player 2 .
std::shared_ptr< Button > Withdraw::getPlayer1IndexNextButton()
Getter for Player 1 offer next property button.
A shared pointer to the next property Button object for Player 1 offer.
std::shared_ptr< Button > Withdraw::getPlayer1IndexPreviousButton()
Getter for Player 1 index previous property button.
A shared pointer to the previous property Button object for Player 1 offer.
std::shared_ptr< Button > Withdraw::getPlayer2IndexNextButton()
Getter for Player 2 index next property button.
A shared pointer to the next property Button object for Player 2 offer.
std::shared_ptr< Button > Withdraw::getPlayer2IndexPreviousButton()
Getter for Player 2 index previous property button.
A shared pointer to the previous property Button object for Player 2 offer.
std::shared_ptr< Button > Withdraw::getPlayer1AddButton()
Getter for Player 1 add to offer property button.
A shared pointer to the add property Button object for Player 1 offer.
std::shared_ptr< Button > Withdraw::getPlayer1RemoveButton()
Getter for Player 1 remove from offer property button.
A shared pointer to the remove property Button object from Player 1 offer.
std::shared_ptr< Button > Withdraw::getPlayer2AddButton()
Getter for Player 2 add to offer property button.
A shared pointer to the add property Button object for Player 2 offer.
std::shared_ptr< Button > Withdraw::getPlayer2RemoveButton()
Getter for Player 2 remove from offer property button.
A shared pointer to the remove property Button object from Player 2 offer.
std::shared_ptr< Button > Withdraw::getResignDecisionButton()
Getter for the resign decision button.
A shared pointer to the resign decision Button object.
std::shared_ptr< Button > Withdraw::getAcceptDecisionButton()
Getter for the accept decision button.
A shared pointer to the accept decision Button object.
void Withdraw::makeWithdraw()
Initiates the withdrawal process (exchange of money and properties).
References Field::getType, PropertyField::setOwner, STATION, STREET, UTILITY.
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::moneyTransferIndex(unsigned int player_num, int money)
Transfers money during the withdrawal process.
player_num An unsigned integer representing the player number (1-2). money An integer representing the amount of money to transfer (can be negative).
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::moneyTextUpdate()
Updates the displayed money text during the withdrawal process.
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::showProperty(int column)
Shows the property details for the specified column during the withdrawal process.
column An integer representing the column index (1-4).
References FOUR_HOUSES, FOUR_STATIONS, getFont, getFontSize, Field::getGraphicPath, Field::getHeight, StreetField::getHotelPrice, StreetField::getHousePrice, PropertyField::getMortgage, Field::getName, PropertyField::getPrice, UtilityField::getRentMultipliers, StreetField::getRentValues, StationField::getRentValues, Field::getType, Field::getWidth, height, HOTEL, NO_HOUSES, ONE_HOUSE, ONE_STATION, ONE_UTILITY, STATION, STREET, THREE_HOUSES, THREE_STATIONS, TWO_HOUESES, TWO_STATIONS, TWO_UTILITIES, width.
Referenced by MonopolyGameEngine::monopolyGameWorker, setValueScreenVisible.
sf::Sprite & Withdraw::getSpritePropertyPlayer1()
Getter for Player 1's property sprite.
A reference to the SFML Sprite object representing Player 1's properties.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & Withdraw::getTextsPropertyPlayer1()
Getter for the text objects representing Player 1's property details.
A vector of shared pointers to SFML Text objects.
Referenced by GameScreen::draw.
sf::Sprite & Withdraw::getSpritePropertyPlayer1Index()
Getter for Player 1's offered property sprite.
A reference to the SFML Sprite object representing Player 1's offered properties.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & Withdraw::getTextsPropertyPlayer1Index()
Getter for the text objects representing Player 1's offered property details.
A vector of shared pointers to SFML Text objects.
Referenced by GameScreen::draw.
sf::Sprite & Withdraw::getSpritePropertyPlayer2()
Getter for Player 2's property sprite.
A reference to the SFML Sprite object representing Player 2's properties.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & Withdraw::getTextsPropertyPlayer2()
Getter for the text objects representing Player 2's property details.
A vector of shared pointers to SFML Text objects.
Referenced by GameScreen::draw.
sf::Sprite & Withdraw::getSpritePropertyPlayer2Index()
Getter for Player 2's offered property sprite.
A reference to the SFML Sprite object representing Player 2's offered properties.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & Withdraw::getTextsPropertyPlayer2Index()
Getter for the text objects representing Player 2's offered property details.
A vector of shared pointers to SFML Text objects.
Referenced by GameScreen::draw.
std::shared_ptr< sf::Texture > Withdraw::getTexturePropertyPlayer1()
Getter for Player 1's property texture.
SFML Texrute object representing Player 1's properties.
Referenced by GameScreen::draw.
std::shared_ptr< sf::Texture > Withdraw::getTexturePropertyPlayer1Index()
Getter for Player 1's offer property texture.
SFML Texrute object representing Player 1's properties offer.
Referenced by GameScreen::draw.
std::shared_ptr< sf::Texture > Withdraw::getTexturePropertyPlayer2()
Getter for Player 2's property texture.
SFML Texrute object representing Player 2's properties.
Referenced by GameScreen::draw.
std::shared_ptr< sf::Texture > Withdraw::getTexturePropertyPlayer2Index()
Getter for Player 2's offer property texture.
SFML Texrute object representing Player 2's properties offer.
Referenced by GameScreen::draw.
void Withdraw::addPropertyPlayerShowed(int i, unsigned int col)
Changes showed property in certain column.
i if i > 0 moves righ in properties vector, if i < 0 moves left col (1-4) defines properties column
Referenced by MonopolyGameEngine::monopolyGameWorker.
void Withdraw::propertyPlayerMoveIndex(int dir, unsigned int plr_num)
Moves properties between players ownership and withdraw offer.
dir if > 0 moves to offer vector, if < 0 moves from offer vectpr plr_num if 1 - active player, if 2 - passive player, in withdraw
Referenced by MonopolyGameEngine::monopolyGameWorker.
bool Withdraw::isNonZeroValue()
Check whenever withdraw is legal to be done.
true if withdraw is legal, otherwise false