ContextWindow
ContextWindow * ContextWindow::context_window_
Static pointer to the ContextWindow instance.
sf::RenderWindow ContextWindow::window_
SFML RenderWindow object for rendering graphics.
Referenced by getWindow, Field::setHeight, Field::setWidth.
sf::View ContextWindow::view_
SFML View object for defining a camera in the 2D scene.
Referenced by getView.
ContextWindow::ContextWindow()
Private constructor to enforce Singleton pattern.
ContextWindow::ContextWindow(ContextWindow &other)=delete
Deleted constructor for proper Singleton class implementation.
void ContextWindow::operator=(const ContextWindow &)=delete
Deleted = operator for proper Singleton class implementation.
void ContextWindow::display()
Displays the contents of the window.
References getWindow.
Referenced by GameEngine::display.
void ContextWindow::clear()
Clears the contents of the window.
References getWindow.
bool ContextWindow::isOpen()
Checks if the window is open.
True if the window is open, false otherwise.
References getWindow.
sf::RenderWindow & ContextWindow::getWindow()
Gets the SFML RenderWindow object.
Reference to the SFML RenderWindow object.
References window_.
Referenced by clear, GameEngine::clear, display, GameMenuScreen::draw, GameScreen::draw, GameEngine::GameEngine, GameMenuScreen::gameMenuCreate, isOpen, MainMenuScreen::mainMenuCreate, GameEngine::pollForEvents.
sf::View & ContextWindow::getView()
Gets the SFML View object.
Reference to the SFML View object.
References view_.
Referenced by GameEngine::GameEngine.
ContextWindow * ContextWindow::GetInstance()
Gets the pointer to the ContextWindow instance.
Pointer to the ContextWindow instance.
Referenced by GameEngine::GameEngine, GameMenuScreen::gameMenuCreate, GameScreen::GameScreen, Field::getContextWindow, MainMenuScreen::mainMenuCreate.