MonopolyGameEngine
TurnState MonopolyGameEngine::turn_state_
Current turn state of the game.
const unsigned int MonopolyGameEngine::PLAYERS_MAX_
Maximum number of players in the game.
const unsigned int MonopolyGameEngine::PLAYERS_MIN_
Minimum number of players in the game.
unsigned int MonopolyGameEngine::players_starting_amount_
Starting amount of money for players.
std::array<unsigned int, 4> MonopolyGameEngine::players_starting_Ids_
Starting IDs for players.
unsigned int MonopolyGameEngine::house_count_
Total count of houses in the game.
unsigned int MonopolyGameEngine::hotel_count_
Total count of hotels in the game.
unsigned int MonopolyGameEngine::player_index_turn_
Index of the current player's turn.
bool MonopolyGameEngine::is_ai_game_only_
Flag indicating whether the game consists only of AI players.
GameScreenType MonopolyGameEngine::screen_type_
Type of the current game screen.
const unsigned int MonopolyGameEngine::PLAYER_MONEY_DEFAULT_
Default starting money for players.
const unsigned int MonopolyGameEngine::START_PASSING_MONEY_
Money passed to players when passing the start position.
const unsigned int MonopolyGameEngine::GAME_TURNS_MAX
Maximum number of turns in the game.
unsigned int MonopolyGameEngine::game_turns_globally_done_
Number of turns globally performed in the game.
std::array<bool, 4> MonopolyGameEngine::game_turn_by_player_done_
Number of turns performed by each player.
AuctionState MonopolyGameEngine::auction_state_
Current state of the auction.
const std::string MonopolyGameEngine::CHANCE_FILE_PATH_
File path for chance cards configuration.
const std::string MonopolyGameEngine::GAMEBOARD_FILE_PATH_
File path for game board configuration.
std::shared_ptr<Board> MonopolyGameEngine::gameboard_
Pointer to the game board.
std::vector<std::shared_ptr<Player> > MonopolyGameEngine::players_
Vector of player objects.
std::vector<std::shared_ptr<Player> > MonopolyGameEngine::players_bankrupted_
Vector of bankrupted players.
const unsigned int MonopolyGameEngine::FONT_SIZE
Font size for text in GUI.
sf::Font MonopolyGameEngine::font_
Font used in the GUI.
std::vector<std::shared_ptr<Button> > MonopolyGameEngine::buttons_
Vector of buttons in the GUI.
std::vector<std::shared_ptr<sf::Text> > MonopolyGameEngine::texts_
Vector of text elements in the GUI.
std::vector<std::shared_ptr<Button> > MonopolyGameEngine::auction_buttons_
Vector of auction buttons in the GUI.
std::vector<std::shared_ptr<sf::Text> > MonopolyGameEngine::auction_texts_
Vector of auction text elements in the GUI.
sf::Vector2f MonopolyGameEngine::ROLL_DICE_BUTTON_POSITION
Position of the roll dice button.
std::shared_ptr<Button> MonopolyGameEngine::roll_dice_button_
Pointer to the roll dice button.
sf::Vector2f MonopolyGameEngine::TURN_INFO_TEXT_POSITION
Position of the turn info text.
std::shared_ptr<sf::Text> MonopolyGameEngine::turn_info_text_
Pointer to the turn info text.
sf::Vector2f MonopolyGameEngine::ROLLED_VALUE_TEXT_POSITION
Position of the rolled value text.
std::shared_ptr<sf::Text> MonopolyGameEngine::rolled_value_text_
Pointer to the rolled value text.
sf::Vector2f MonopolyGameEngine::PLAYERS_INFO_TEXT_POSITION
Position of the players info text.
std::array<std::vector<std::shared_ptr<sf::Text> >, 4> MonopolyGameEngine::player_info_text_
Array of vectors containing player info text elements.
sf::Vector2f MonopolyGameEngine::BUY_BUTTON_POSITION
Position of the buy button.
std::shared_ptr<Button> MonopolyGameEngine::buy_field_button_
Pointer to the buy field button.
std::shared_ptr<Button> MonopolyGameEngine::resign_buy_field_button_
Pointer to the resign buy field button.
sf::Vector2f MonopolyGameEngine::PROPERTY_DATA_POSITION
Position of the property data.
sf::Vector2f MonopolyGameEngine::PROPERTY_DATA_AUCTION_POSITION
Position of the property data during an auction.
float MonopolyGameEngine::PROPERTY_DATA_SCALE
Scale factor for property data.
sf::Sprite MonopolyGameEngine::property_data_sprite_
Sprite for property data.
sf::Texture MonopolyGameEngine::property_data_texture_
Texture for property data.
std::vector<std::shared_ptr<sf::Text> > MonopolyGameEngine::property_data_texts_
Vector of property data text elements.
sf::Vector2f MonopolyGameEngine::ALL_PROPERTY_DATA_POSITION
Position of all property data.
sf::Sprite MonopolyGameEngine::all_property_data_sprite_
Sprite for all property data.
sf::Texture MonopolyGameEngine::all_property_data_texture_
Texture for all property data.
std::vector<std::shared_ptr<sf::Text> > MonopolyGameEngine::all_property_data_texts_
Vector of all property data text elements.
sf::Vector2f MonopolyGameEngine::NEXT_PROPERTY_BUTTON_POSITION
Position of the next property button.
sf::Vector2f MonopolyGameEngine::PREVIOUS_PROPERTY_BUTTON_POSITION
Position of the previous property button.
std::shared_ptr<Button> MonopolyGameEngine::next_property_button_
Pointer to the next property button.
std::shared_ptr<Button> MonopolyGameEngine::previous_property_button_
Pointer to the previous property button.
unsigned int MonopolyGameEngine::current_property_showed_
Index of the currently displayed property.
std::shared_ptr<sf::Text> MonopolyGameEngine::available_houses_text_
Pointer to the text displaying available houses.
std::shared_ptr<sf::Text> MonopolyGameEngine::availableH_hotels_text_
Pointer to the text displaying available hotels.
sf::Vector2f MonopolyGameEngine::AVAILABLE_HOUSE_TEXT_POSITION
Position of the available houses text.
std::shared_ptr<sf::Text> MonopolyGameEngine::bidded_property_text_
Pointer to the text displaying the bidded property.
sf::Vector2f MonopolyGameEngine::BIDDED_PROPERTY_TEXT_POSITION
Position of the bidded property text.
std::shared_ptr<sf::Text> MonopolyGameEngine::bidder_info_text_
Pointer to the text displaying bidder information.
sf::Vector2f MonopolyGameEngine::BIDDER_INFO_TEXT_POSITION
Position of the bidder info text.
std::shared_ptr<sf::Text> MonopolyGameEngine::highest_bid_info_text_
Pointer to the text displaying the highest bid information.
sf::Vector2f MonopolyGameEngine::HIGHEST_BID_TEXT_POSITION
Position of the highest bid text.
std::shared_ptr<sf::Text> MonopolyGameEngine::leading_bidder_info_text_
Pointer to the text displaying the leading bidder information.
sf::Vector2f MonopolyGameEngine::LEADING_BIDDER_TEXT_POSITION
Position of the leading bidder text.
std::shared_ptr<sf::Text> MonopolyGameEngine::current_offer_info_text_
Pointer to the text displaying the current offer information.
sf::Vector2f MonopolyGameEngine::CURRENT_OFFER_TEXT_POSITION
Position of the current offer text.
std::shared_ptr<sf::Text> MonopolyGameEngine::house_text_
Pointer to the text displaying the number of houses.
std::shared_ptr<sf::Text> MonopolyGameEngine::hotel_text_
Pointer to the text displaying the number of hotels.
sf::Vector2f MonopolyGameEngine::HOUSE_TEXT_POSITION
Position of the house text.
sf::Vector2f MonopolyGameEngine::HOTEL_TEXT_POSITION
Position of the hotel text.
std::shared_ptr<Button> MonopolyGameEngine::buy_house_button_
Pointer to the buy house button.
std::shared_ptr<Button> MonopolyGameEngine::sell_house_button_
Pointer to the sell house button.
std::shared_ptr<Button> MonopolyGameEngine::buy_hotel_button_
Pointer to the buy hotel button.
std::shared_ptr<Button> MonopolyGameEngine::sell_hotel_button_
Pointer to the sell hotel button.
sf::Vector2f MonopolyGameEngine::BUY_HOUSE_BUTTON_POSITION
Position of the buy house button.
sf::Vector2f MonopolyGameEngine::SELL_HOUSE_BUTTON_POSITION
Position of the sell house button.
sf::Vector2f MonopolyGameEngine::BUY_HOTEL_BUTTON_POSITION
Position of the buy hotel button.
sf::Vector2f MonopolyGameEngine::SELL_HOTEL_BUTTON_POSITION
Position of the sell hotel button.
std::shared_ptr<Button> MonopolyGameEngine::bankrupt_button_
Pointer to the bankrupt button.
std::shared_ptr<Button> MonopolyGameEngine::next_turn_button_
Pointer to the next turn button.
sf::Vector2f MonopolyGameEngine::BANKRUPT_BUTTON_POSITION
Position of the bankrupt button.
sf::Vector2f MonopolyGameEngine::NEXT_TURN_BUTTON_POSITION
Position of the next turn button.
sf::Vector2f MonopolyGameEngine::house_size_
Size of a house.
sf::Texture MonopolyGameEngine::house_texture_
Texture for a house.
sf::Texture MonopolyGameEngine::hotel_texture_
Texture for a hotel.
std::shared_ptr<Button> MonopolyGameEngine::jail_pay_button_
Pointer to the pay jail button.
sf::Vector2f MonopolyGameEngine::JAIL_PAY_BUTTON_POSITION
Position of the pay jail button.
const unsigned int MonopolyGameEngine::JAIL_PAY_MONEY
Amount of money required to pay jail.
std::shared_ptr<sf::Text> MonopolyGameEngine::Text1_
Pointer to the text displaying the value 1 in auction offer.
std::shared_ptr<sf::Text> MonopolyGameEngine::Text10_
Pointer to the text displaying the value 10 in auction offer.
std::shared_ptr<sf::Text> MonopolyGameEngine::Text100_
Pointer to the text displaying the value 100 in auction offer.
sf::Vector2f MonopolyGameEngine::TEXT_1_POSITION
Position of the text displaying the value 1.
sf::Vector2f MonopolyGameEngine::TEXT_10_POSITION
Position of the text displaying the value 10.
sf::Vector2f MonopolyGameEngine::TEXT_100_POSITION
Position of the text displaying the value 100.
std::shared_ptr<Button> MonopolyGameEngine::add_1_to_offer_button_
Pointer to the add 1 to offer button in auction.
std::shared_ptr<Button> MonopolyGameEngine::add_10_to_offer_button_
Pointer to the add 10 to offer button in auction.
std::shared_ptr<Button> MonopolyGameEngine::add_100_to_offer_button_
Pointer to the add 100 to offer button in auction.
std::shared_ptr<Button> MonopolyGameEngine::substract_1_from_offer_button_
Pointer to the subtract 1 from offer button in auction.
std::shared_ptr<Button> MonopolyGameEngine::substract_10_from_offer_button_
Pointer to the subtract 10 from offer button in auction.
std::shared_ptr<Button> MonopolyGameEngine::substract_100_from_offer_button_
Pointer to the subtract 100 from offer button in auction.
sf::Vector2f MonopolyGameEngine::ADD_1_BUTTON_POSITION
Position of the add 1 button.
sf::Vector2f MonopolyGameEngine::ADD_10_BUTTON_POSITION
Position of the add 10 button.
sf::Vector2f MonopolyGameEngine::ADD_100_BUTTON_POSITION
Position of the add 100 button.
sf::Vector2f MonopolyGameEngine::SUBSTRACT_1_BUTTON_POSITION
Position of the subtract 1 button.
sf::Vector2f MonopolyGameEngine::SUBSTRACT_10_BUTTON_POSITION
Position of the subtract 10 button.
sf::Vector2f MonopolyGameEngine::SUBSTRACT_100_BUTTON_POSITION
Position of the subtract 100 button.
std::shared_ptr<Button> MonopolyGameEngine::auction_bid_button_
Pointer to the auction bid button.
sf::Vector2f MonopolyGameEngine::AUCTION_BID_BUTTON_POSITION
Position of the auction bid button.
std::shared_ptr<Button> MonopolyGameEngine::auction_resign_button_
Pointer to the auction resign button.
sf::Vector2f MonopolyGameEngine::AUCTION_RESIGN_BUTTON_POSITION
Position of the auction resign button.
Withdraw MonopolyGameEngine::withdraw_
Object representing player withdrawal.
std::shared_ptr<Button> MonopolyGameEngine::withdraw_button_
Pointer to the withdraw button.
sf::Vector2f MonopolyGameEngine::WITHDRAW_BUTTON_POSITION
Position of the withdraw button.
std::shared_ptr<Button> MonopolyGameEngine::mortgage_button_
Pointer to the mortgage button.
std::shared_ptr<Button> MonopolyGameEngine::unmortgage_button_
Pointer to the unmortgage button.
sf::Vector2f MonopolyGameEngine::MORTGAGE_BUTTON_POSITION
Position of the mortgage button.
sf::Vector2f MonopolyGameEngine::UNMORTGAGE_BUTTON_POSITION
Position of the unmortgage button.
std::vector<ChanceCard> MonopolyGameEngine::chance_cards_
Vector of chance cards.
unsigned int MonopolyGameEngine::chance_card_current_
Index of the current chance card.
NotificationWall MonopolyGameEngine::notifications_wall_
Notification wall for displaying messages.
float MonopolyGameEngine::RESULT_DATA_Y
Y-coordinate for positioning result screen data.
std::vector<std::shared_ptr<sf::Text> > MonopolyGameEngine::result_players_places_
Vector of result screen player places.
std::shared_ptr<Button> MonopolyGameEngine::return_to_main_menu_button_
Pointer to the return to main menu button.
std::ofstream MonopolyGameEngine::file_logger
const std::string MonopolyGameEngine::FILE_LOGGER_PATH
unsigned int MonopolyGameEngine::getplayer_index_turn() const
Gets the current player index of the turn.
The current player index.
void MonopolyGameEngine::incplayer_index_turn()
Increases the player index for the next turn.
void MonopolyGameEngine::setTurnState(TurnState new_state)
Sets the turn state to the specified state.
new_state The new turn state.
void MonopolyGameEngine::buttonsWorker()
Handles various button-related actions.
sf::Vector2f MonopolyGameEngine::getUpdatePlayerSpritePosition()
Gets the updated position for the player sprite.
The updated position.
void MonopolyGameEngine::clearPropertyData(bool is_property_shown_to_buy)
Clears property data based on whether it is shown for purchase or not.
is_property_shown_to_buy Flag indicating whether the property is shown for purchase.
unsigned int MonopolyGameEngine::getFieldPriceByPosition(unsigned int pos)
Gets the field price based on its position.
pos The position of the field. The price of the field.
void MonopolyGameEngine::addOwnerToPropertyField(std::shared_ptr< Player > player, unsigned int pos)
Adds the owner to a property field.
player The player becoming the owner. pos The position of the property field.
bool MonopolyGameEngine::isButtonClicked(std::shared_ptr< Button > button_ptr)
Checks if a button is clicked.
button_ptr The pointer to the button. True if the button is clicked, false otherwise.
unsigned int MonopolyGameEngine::rollDice() const
Rolls the dice and returns the result.
The rolled dice value.
void MonopolyGameEngine::movePlayer(unsigned int turn_index, unsigned int position_increment)
Moves the player based on the turn index and position increment.
turn_index The index of the player's turn. position_increment The increment in the player's position.
void MonopolyGameEngine::sendToJail(unsigned int turn_index)
Sends the player to jail based on the turn index.
turn_index The index of the player's turn.
void MonopolyGameEngine::notificationAdd(unsigned int index, std::string text)
Adds a notification based on the index and text.
index The index of the notification. text The text of the notification.
void MonopolyGameEngine::handlePassingStart(unsigned int old_pos, unsigned int new_pos)
Handles passing the Start position, updating old and new positions.
old_pos The old position of the player. new_pos The new position of the player.
void MonopolyGameEngine::makePlayerBankrupt(unsigned int player_index_turn)
Makes the player bankrupt based on the player's index.
player_index_turn The index of the player.
void MonopolyGameEngine::showAllPropertiesWorker()
Shows all properties for purchase.
void MonopolyGameEngine::boardToAuctionSwitchHandler(bool is_auction)
Switches the game window to auction mode based on the specified flag.
is_auction Flag indicating whether to switch to auction mode.
void MonopolyGameEngine::withdrawWorker()
Handles withdrawal actions.
void MonopolyGameEngine::aiWithdrawWorker()
Handles AI withdrawal actions.
ChanceCard & MonopolyGameEngine::getChanceCard()
Gets the chance card reference.
The chance card reference.
void MonopolyGameEngine::updateChanceCard()
Updates the chance card.
bool MonopolyGameEngine::gameFinishedCheckWinner()
Checks if the game has finished and determined a winner.
True if there is a winner, false otherwise.
bool MonopolyGameEngine::gameFinishedCheckDraw()
Checks if the game has finished in a draw.
True if the game is a draw, false otherwise.
void MonopolyGameEngine::gameTurnsCounterHandle()
Handles the counter for game turns.
void MonopolyGameEngine::removePlayerFromGame(unsigned int player_index_turn, bool is_draw)
Removes the player from the game based on the player's index and draw status.
player_index_turn The index of the player. is_draw Flag indicating whether the game ended in a draw.
std::shared_ptr< Button > MonopolyGameEngine::createDefaultButton(sf::String text, unsigned int width, unsigned int height)
Creates a default button with the specified text, width, and height.
text The text of the button. width The width of the button. height The height of the button. A shared pointer to the created button.
void MonopolyGameEngine::fileLoggerOpen()
Opens the file logger.
void MonopolyGameEngine::fileLoggerWrite(std::string text)
Writes text to the file logger.
text The text to write.
void MonopolyGameEngine::fileLoggerClose()
Closes the file logger.
MonopolyGameEngine::MonopolyGameEngine()
Constructor for the monopolyGameEngine class.
References ROLL_DICE.
void MonopolyGameEngine::setScreenType(GameScreenType new_screen_type)
Sets the screen type to the specified type.
new_screen_type The new screen type.
Referenced by monopolyGameWorker.
GameScreenType MonopolyGameEngine::getScreenType() const
Gets the current screen type.
The current screen type.
Referenced by GameScreen::draw, monopolyGameWorker.
void MonopolyGameEngine::createButtonRollDice()
Creates the button for rolling the dice.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextTurnInfo()
Creates text for displaying turn information.
References addText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextrolled_value()
Creates text for displaying the rolled dice value.
References addText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextPlayersInfo()
Creates text for displaying players' information.
References addText, getBoard, getFont, getFontSize, Field::getName.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::updateTextPlayersInfo()
Updates the text displaying players' information.
References getBoard, Field::getName.
Referenced by monopolyGameWorker.
void MonopolyGameEngine::createTextBiddedProperty()
Creates text for displaying information about the bidded property.
References addAuctionText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextBidderInfo()
Creates text for displaying information about the bidder.
References addAuctionText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextHighestBidInfo()
Creates text for displaying the highest bid in an auction.
References addAuctionText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createTextLeadingBidderInfo()
Creates text for displaying information about the leading bidder in an auction.
References addAuctionText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createCurrentOfferBidderInfo()
Creates text for displaying the current offer in an auction.
References addAuctionText, getFont, getFontSize.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonBuyResign()
Creates a button for buying or resigning from a property.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonNextProperty()
Creates a button for moving to the next property.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonPerviousProperty()
Creates a button for moving to the previous property.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonsBuySellHouseHotel()
Creates buttons for buying, selling houses, and hotels.
References addButton, addText, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonsBankrupt()
Creates buttons for handling bankruptcy.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonsNextTurn()
Creates buttons for moving to the next turn.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonsJailPay()
Creates buttons for handling actions related to the jail (paying to get out).
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createAuctionOfferButtons()
Creates buttons for handling auction offers.
References addAuctionButton, addAuctionText, addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createAuctionBidButton()
Creates a button for participating in an auction by bidding.
References addAuctionButton, addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createAuctionResignButton()
Creates a button for resigning from an auction.
References addAuctionButton, addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createButtonWithdraw()
Creates a button for withdrawing from the game.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createMortagingButton()
Creates buttons for mortgaging properties.
References addButton, getFont, getFontSize, IDLE.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createResultScreenStuff()
Creates various elements for the result screen.
References addButton, getFont, getFontSize, RETURN_TO_MAIN_MENU.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::updateResultScreenStuff()
Updates elements on the result screen.
References getButtons, getFont, getFontSize.
Referenced by monopolyGameWorker.
void MonopolyGameEngine::showPropertyData(unsigned int pos, bool is_property_shown_to_buy)
Shows property data on the GUI based on the position and whether it is shown to buy.
pos The position of the property. is_property_shown_to_buy Indicates whether the property information is shown for buying.
References FOUR_HOUSES, FOUR_STATIONS, getBoard, getFont, getFontSize, Field::getGraphicPath, Field::getHeight, StreetField::getHotelPrice, StreetField::getHousePrice, PropertyField::getMortgage, Field::getName, PropertyField::getPrice, UtilityField::getRentMultipliers, StreetField::getRentValues, StationField::getRentValues, Field::getType, Field::getWidth, height, HOTEL, NO_HOUSES, ONE_HOUSE, ONE_STATION, ONE_UTILITY, STATION, STREET, THREE_HOUSES, THREE_STATIONS, TWO_HOUESES, TWO_STATIONS, TWO_UTILITIES, width.
Referenced by GameScreen::GameScreen, monopolyGameWorker.
void MonopolyGameEngine::turnInfoTextShow()
Displays text related to turn information.
Referenced by GameScreen::GameScreen, monopolyGameWorker.
sf::Font & MonopolyGameEngine::getFont()
Returns the font used in the GUI.
Reference to the font.
Referenced by createAuctionBidButton, createAuctionOfferButtons, createAuctionResignButton, createAvailableHousesHotelText, createButtonBuyResign, createButtonNextProperty, createButtonPerviousProperty, createButtonRollDice, createButtonsBankrupt, createButtonsBuySellHouseHotel, createButtonsJailPay, createButtonsNextTurn, createButtonWithdraw, createCurrentOfferBidderInfo, createMortagingButton, createResultScreenStuff, createTextBiddedProperty, createTextBidderInfo, createTextHighestBidInfo, createTextLeadingBidderInfo, createTextPlayersInfo, createTextrolled_value, createTextTurnInfo, getPropertyNameToDraw, showPropertyData, updateResultScreenStuff.
unsigned int MonopolyGameEngine::getFontSize() const
Returns the font size used in the GUI.
Font size.
Referenced by createAuctionBidButton, createAuctionOfferButtons, createAuctionResignButton, createAvailableHousesHotelText, createButtonBuyResign, createButtonNextProperty, createButtonPerviousProperty, createButtonRollDice, createButtonsBankrupt, createButtonsBuySellHouseHotel, createButtonsJailPay, createButtonsNextTurn, createButtonWithdraw, createCurrentOfferBidderInfo, createMortagingButton, createResultScreenStuff, createTextBiddedProperty, createTextBidderInfo, createTextHighestBidInfo, createTextLeadingBidderInfo, createTextPlayersInfo, createTextrolled_value, createTextTurnInfo, getPropertyNameToDraw, showPropertyData, updateResultScreenStuff.
void MonopolyGameEngine::setFont(sf::Font font)
Sets the font to be used in the GUI.
font Font to be set.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::addButton(std::shared_ptr< Button > button_tmp)
Adds a button to the GUI.
button_tmp Pointer to the button to be added.
Referenced by createAuctionBidButton, createAuctionOfferButtons, createAuctionResignButton, createButtonBuyResign, createButtonNextProperty, createButtonPerviousProperty, createButtonRollDice, createButtonsBankrupt, createButtonsBuySellHouseHotel, createButtonsJailPay, createButtonsNextTurn, createButtonWithdraw, createMortagingButton, createResultScreenStuff, GameScreen::GameScreen.
void MonopolyGameEngine::addText(std::shared_ptr< sf::Text > text_tmp)
Adds text to the GUI.
text_tmp Pointer to the text to be added.
Referenced by createAvailableHousesHotelText, createButtonsBuySellHouseHotel, createTextPlayersInfo, createTextrolled_value, createTextTurnInfo.
void MonopolyGameEngine::addAuctionButton(std::shared_ptr< Button > button_tmp)
Adds an auction button to the GUI.
button_tmp Pointer to the auction button to be added.
Referenced by createAuctionBidButton, createAuctionOfferButtons, createAuctionResignButton.
void MonopolyGameEngine::addAuctionText(std::shared_ptr< sf::Text > text_tmp)
Adds auction text to the GUI.
text_tmp Pointer to the auction text to be added.
Referenced by createAuctionOfferButtons, createCurrentOfferBidderInfo, createTextBiddedProperty, createTextBidderInfo, createTextHighestBidInfo, createTextLeadingBidderInfo.
std::vector< std::shared_ptr< Button > > & MonopolyGameEngine::getButtons()
Returns a vector of pointers to buttons in the GUI.
Vector of pointers to buttons.
Referenced by GameScreen::draw, updateResultScreenStuff, GameScreen::worker.
std::vector< std::shared_ptr< sf::Text > > & MonopolyGameEngine::getTexts()
Returns a vector of pointers to text elements in the GUI.
Vector of pointers to text elements.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< Button > > & MonopolyGameEngine::getAuctionButtons()
Returns a vector of pointers to auction buttons in the GUI.
Vector of pointers to auction buttons.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & MonopolyGameEngine::getAuctionTexts()
Returns a vector of pointers to auction text elements in the GUI.
Vector of pointers to auction text elements.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & MonopolyGameEngine::getResultTexts()
Returns a vector of pointers to text elements used in the result screen.
Vector of pointers to result screen text elements.
Referenced by GameScreen::draw.
sf::Sprite & MonopolyGameEngine::getPropertyDataSprite()
Returns the sprite representing property data in the GUI.
Reference to the property data sprite.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & MonopolyGameEngine::getPropertyDataTexts()
Returns a vector of pointers to text elements representing property data in the GUI.
Vector of pointers to property data text elements.
Referenced by GameScreen::draw.
sf::Sprite & MonopolyGameEngine::getAllPropertyDataSprite()
Returns the sprite representing all property data in the GUI.
Reference to the all property data sprite.
Referenced by GameScreen::draw.
std::vector< std::shared_ptr< sf::Text > > & MonopolyGameEngine::getAllPropertyDataTexts()
Returns a vector of pointers to text elements representing all property data in the GUI.
Vector of pointers to all property data text elements.
Referenced by GameScreen::draw.
NotificationWall & MonopolyGameEngine::getNotificationsWall()
Returns the notification wall used in the GUI.
Reference to the notification wall.
Referenced by GameScreen::draw.
sf::Text MonopolyGameEngine::getPropertyNameToDraw(sf::Text text, sf::Sprite &sprite, float rotation)
Gets the text suitable for drawing a property name.
text Original text to be drawn. sprite Reference to the sprite associated with the property. rotation Rotation angle of the text. Modified text for drawing.
References getFont, getFontSize.
Referenced by GameScreen::draw.
sf::Texture & MonopolyGameEngine::getHouseTexture()
Returns the texture of the house used in the GUI.
Reference to the house texture.
Referenced by GameScreen::draw, getHotelSprite, getHouseSprite.
sf::Texture & MonopolyGameEngine::getHotelTexture()
Returns the texture of the hotel used in the GUI.
Reference to the hotel texture.
Referenced by GameScreen::draw.
sf::Vector2f & MonopolyGameEngine::getHouseSize()
Returns the size of a house in the GUI.
Reference to the house size.
Referenced by getHotelSprite, getHouseSprite.
void MonopolyGameEngine::createPlayers(std::vector< std::shared_ptr< Player >> &players_from_game_engine)
Creates player objects based on input vector.
players_from_game_engine Vector of pointers to players.
References Field::getHeight, Field::getWidth, Player::setAiLevel, Player::setId, Player::setIsAi, AiPlayer::setNeuralNetwork.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::clearPlayers()
Clears player objects from the game.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::createBoard()
Creates the game board.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::clearBoard()
Clears the game board.
std::shared_ptr< Board > MonopolyGameEngine::getBoard()
Returns a pointer to the game board.
Pointer to the game board.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker, calculateRent, colorGroupEmpty, createTextPlayersInfo, GameScreen::draw, GameScreen::GameScreen, isBuildingLegal, isDestroyingLegal, isHotelBuildingLegal, isHotelDestroyingLegal, monopolyGameWorker, performAuction, showPropertyData, updateTextPlayersInfo.
std::vector< std::shared_ptr< Player > > & MonopolyGameEngine::getPlayers()
Returns a vector of pointers to players in the game.
Vector of pointers to players.
Referenced by GameScreen::draw, monopolyGameWorker.
std::vector< std::shared_ptr< Player > > MonopolyGameEngine::getPlayersResult()
Returns a vector of pointers to players based on game result.
Vector of pointers to players.
Referenced by GameScreen::getPlayersResult.
void MonopolyGameEngine::setplayer_index_turn(unsigned int indx)
Sets the index of the player whose turn it is.
indx Index of the player.
Referenced by GameScreen::GameScreen.
TurnState MonopolyGameEngine::getTurnState() const
Gets the current turn state.
Current turn state.
Referenced by GameScreen::draw, monopolyGameWorker.
void MonopolyGameEngine::setAuctionState(AuctionState new_state)
Sets the state of the auction.
new_state New state of the auction.
Referenced by monopolyGameWorker, performAuction.
AuctionState MonopolyGameEngine::getAuctionState()
Gets the current state of the auction.
Current state of the auction.
Referenced by monopolyGameWorker, performAuction.
unsigned int MonopolyGameEngine::getHouseCount()
Gets the count of houses available for purchase.
Count of houses.
Referenced by createAvailableHousesHotelText, isBuildingLegal, isHotelDestroyingLegal, updateAvailableHousesHotelText.
unsigned int MonopolyGameEngine::getHotelCount()
Gets the count of hotels available for purchase.
Count of hotels.
Referenced by createAvailableHousesHotelText, isHotelBuildingLegal, updateAvailableHousesHotelText.
void MonopolyGameEngine::setHouseCount(unsigned int new_count)
Sets the count of houses available for purchase.
new_count New count of houses.
Referenced by addHouses, substractHouses.
void MonopolyGameEngine::setHotelCount(unsigned int new_count)
Sets the count of hotels available for purchase.
new_count New count of hotels.
Referenced by addHotels, substractHotels.
void MonopolyGameEngine::addHouses(unsigned int added_amount)
Adds houses to the available count.
added_amount Amount to be added.
References setHouseCount.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
void MonopolyGameEngine::substractHouses(unsigned int substracted_amount)
Subtracts houses from the available count.
substracted_amount Amount to be subtracted.
References setHouseCount.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
void MonopolyGameEngine::addHotels(unsigned int added_amount)
Adds hotels to the available count.
added_amount Amount to be added.
References setHotelCount.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
void MonopolyGameEngine::substractHotels(unsigned int substracted_amount)
Subtracts hotels from the available count.
substracted_amount Amount to be subtracted.
References setHotelCount.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
void MonopolyGameEngine::performAuction()
Performs the auction.
References BIDDING, ENDING, getAuctionState, getBoard, PropertyField::getPrice, Field::getType, INITIALIZATION, NO_AUCTION, PASS_BIDDING_TURN, setAuctionState, STATION, STREET, UTILITY.
Referenced by monopolyGameWorker.
unsigned int MonopolyGameEngine::calculateGroupFieldsOwned(std::vector< unsigned int > player_fields, PropertyField &field) const
Calculates the number of group fields owned by a player.
player_fields Vector of field positions owned by the player. field Property field to check for group completion. Number of group fields owned.
References PropertyField::getGroupMembers.
Referenced by calculateRent.
bool MonopolyGameEngine::groupCompleted(std::vector< unsigned int > player_fields, PropertyField &field) const
Checks if a group of properties is completed by a player.
player_fields Vector of field positions owned by the player. field Property field to check for group completion. True if the group is completed, false otherwise.
References PropertyField::getGroupMembers.
Referenced by calculateRent, colorGroupEmpty, isBuildingLegal, isDestroyingLegal, isHotelBuildingLegal, isHotelDestroyingLegal.
bool MonopolyGameEngine::isBuildingLegal(std::shared_ptr< Player > builder, StreetField field)
Checks if building houses on a street is legal for a player.
builder Player attempting to build houses. field Street field to build houses on. True if building is legal, false otherwise.
References getBoard, PropertyField::getGroupMembers, getHouseCount, StreetField::getHouseNumber, StreetField::getHousePrice, PropertyField::getIsMortgaged, groupCompleted.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
bool MonopolyGameEngine::isDestroyingLegal(std::shared_ptr< Player > builder, StreetField field)
Checks if destroying houses on a street is legal for a player.
builder Player attempting to destroy houses. field Street field to destroy houses on. True if destroying is legal, false otherwise.
References getBoard, PropertyField::getGroupMembers, StreetField::getHouseNumber, PropertyField::getIsMortgaged, groupCompleted.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
bool MonopolyGameEngine::isHotelBuildingLegal(std::shared_ptr< Player > builder, StreetField &field)
Checks if building a hotel on a street is legal for a player.
builder Player attempting to build a hotel. field Street field to build a hotel on. True if building a hotel is legal, false otherwise.
References getBoard, PropertyField::getGroupMembers, getHotelCount, StreetField::getHotelPrice, StreetField::getHouseNumber, StreetField::getIsHotel, PropertyField::getIsMortgaged, groupCompleted.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
bool MonopolyGameEngine::isHotelDestroyingLegal(std::shared_ptr< Player > builder, StreetField &field)
Checks if destroying a hotel on a street is legal for a player.
builder Player attempting to destroy a hotel. field Street field to destroy a hotel on. True if destroying a hotel is legal, false otherwise.
References getBoard, PropertyField::getGroupMembers, getHouseCount, StreetField::getIsHotel, PropertyField::getIsMortgaged, groupCompleted.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
bool MonopolyGameEngine::colorGroupEmpty(std::shared_ptr< Player > mortgaging, StreetField &field)
Checks if a color group is empty (no properties owned) for a player.
mortgaging Player attempting to mortgage properties. field Street field to check for a color group. True if the color group is empty, false otherwise.
References getBoard, PropertyField::getGroupMembers, StreetField::getHouseNumber, groupCompleted.
Referenced by aiBuildingsMangingWorker, buildingsManagingWorker.
sf::Sprite MonopolyGameEngine::getHouseSprite(StreetField &field, unsigned int houses_number)
Gets the sprite for a house on a street.
field Street field to get the house sprite for. houses_number Number of houses on the street. Sprite of the house.
References getHouseSize, getHouseTexture, Field::getPosition, Field::getRotation.
Referenced by GameScreen::draw.
sf::Sprite MonopolyGameEngine::getHotelSprite(StreetField &field)
Gets the sprite for a hotel on a street.
field Street field to get the hotel sprite for. Sprite of the hotel.
References getHouseSize, getHouseTexture, Field::getPosition, Field::getRotation.
Referenced by GameScreen::draw.
void MonopolyGameEngine::createAvailableHousesHotelText()
Creates text displaying the available count of houses and hotels.
References addText, getFont, getFontSize, getHotelCount, getHouseCount.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::updateAvailableHousesHotelText()
Updates the text displaying the available count of houses and hotels.
References getHotelCount, getHouseCount.
Referenced by monopolyGameWorker.
unsigned int MonopolyGameEngine::calculateRent(unsigned int rolled_val, int pos)
Calculates the rent to be paid based on the rolled dice value and property position.
rolled_val Rolled dice value. pos Property position. Calculated rent amount.
References calculateGroupFieldsOwned, FOUR_HOUSES, FOUR_STATIONS, getBoard, StreetField::getHouseNumber, StreetField::getIsHotel, PropertyField::getIsMortgaged, PropertyField::getOwner, UtilityField::getRentMultipliers, StreetField::getRentValues, StationField::getRentValues, Field::getType, groupCompleted, HOTEL, NO_HOUSES, ONE_HOUSE, ONE_STATION, ONE_UTILITY, STATION, STREET, THREE_HOUSES, THREE_STATIONS, TWO_HOUESES, TWO_STATIONS, TWO_UTILITIES, UTILITY.
Referenced by monopolyGameWorker.
void MonopolyGameEngine::buildingsManagingWorker()
Worker method for managing building and destroying houses/hotels.
References addHotels, addHouses, colorGroupEmpty, getBoard, StreetField::getHotelPrice, StreetField::getHouseNumber, StreetField::getHousePrice, PropertyField::getIsMortgaged, PropertyField::getMortgage, Field::getName, PropertyField::getOwner, Field::getType, PropertyField::getUnmortgageValue, isBuildingLegal, isDestroyingLegal, isHotelBuildingLegal, isHotelDestroyingLegal, StreetField::setHouseNumber, StreetField::setIsHotel, PropertyField::setIsMortgaged, STATION, STREET, substractHotels, substractHouses, UTILITY.
Referenced by monopolyGameWorker.
void MonopolyGameEngine::aiBuildingsMangingWorker()
AI worker method for managing building and destroying houses/hotels.
References addHotels, addHouses, colorGroupEmpty, getBoard, StreetField::getHotelPrice, StreetField::getHouseNumber, StreetField::getHousePrice, Field::getId, StreetField::getIsHotel, PropertyField::getIsMortgaged, PropertyField::getMortgage, Field::getName, Field::getType, PropertyField::getUnmortgageValue, isBuildingLegal, isDestroyingLegal, isHotelBuildingLegal, isHotelDestroyingLegal, StreetField::setHouseNumber, StreetField::setIsHotel, PropertyField::setIsMortgaged, STATION, STREET, substractHotels, substractHouses, UTILITY, YES.
Referenced by monopolyGameWorker.
bool MonopolyGameEngine::monopolyGameWorker()
Main Worker method for whole monopoly game engine.
References Withdraw::addPropertyPlayerShowed, aiBuildingsMangingWorker, AUCTION, BANK_PAYS_YOU, BOARDGAME, buildingsManagingWorker, BUY, BUY_ACTION, calculateRent, CHANCE, FIELD_ACTION, GET_OUT_OF_JAIL_CARD, getAuctionState, getBoard, StreetField::getHouseNumber, StreetField::getIsHotel, Field::getName, PropertyField::getOwner, getPlayers, getScreenType, TaxField::getTaxValue, ChanceCard::getText, getTurnState, ChanceCard::getType, Field::getType, ChanceCard::getValue, getWithdraw, GO_TO_JAIL, GO_TO_JAIL_CARD, INITIALIZATION, Withdraw::makeWithdraw, Withdraw::moneyTextUpdate, Withdraw::moneyTransferIndex, MOVEMENT_SPACES, MOVEMENT_TO_PROPERTY, NO, NO_AUCTION, NO_TURN, PAY, PAY_FOR_HOUSE_HOTEL, PAY_PLAYERS, PAY_RENT, performAuction, Withdraw::propertyPlayerMoveIndex, RESIGN, RESULT, ROLL_DICE, setAuctionState, Withdraw::setChooseScreenVisible, Withdraw::setDecisionScreenVisible, Withdraw::setPlayer2ToWithdraw, setScreenType, Withdraw::setValueScreenVisible, Withdraw::showProperty, showPropertyData, STATION, STREET, TAX, TAX_CARD, TURN_END, turnInfoTextShow, updateAvailableHousesHotelText, updateResultScreenStuff, updateTextPlayersInfo, UTILITY, WITHDRAW_ADD_VALUE, WITHDRAW_CHOOSE_PLAYER, WITHDRAW_DECISION, WITHDRAW_ONGOING, YES.
Referenced by GameScreen::worker.
Withdraw & MonopolyGameEngine::getWithdraw()
Returns a reference to the Withdraw object.
Withdraw& Reference to the Withdraw object.
Referenced by GameScreen::draw, GameScreen::GameScreen, monopolyGameWorker.
void MonopolyGameEngine::createChanceCards()
Creates the chance cards for the game.
This method initializes and populates the collection of ChanceCard objects used in the game.
References BANK_PAYS_YOU, GET_OUT_OF_JAIL_CARD, GO_TO_JAIL_CARD, MOVEMENT_SPACES, MOVEMENT_TO_PROPERTY, MOVEMENT_WITH_BUY_OR_PAY, PAY_FOR_HOUSE_HOTEL, PAY_PLAYERS, shuffleChanceCards, TAX_CARD.
Referenced by GameScreen::GameScreen.
void MonopolyGameEngine::shuffleChanceCards()
Shuffles the chance cards.
This method shuffles the collection of ChanceCard objects to randomize the order in which they will be drawn during the game.
Referenced by createChanceCards.