NotificationWall
unsigned int NotificationWall::MAX_NOTIFICATIONS_
Maximum number of notifications to display.
sf::Vector2f NotificationWall::DRAW_OFFSET_
Offset for drawing notifications on the screen.
unsigned int NotificationWall::Y_STEP_OFFSET_
Vertical step offset between notifications.
std::vector<std::shared_ptr<sf::Text> > NotificationWall::wall_texts_
Vector to store shared pointers to sf::Text for notifications.
unsigned int NotificationWall::FONT_SIZE_
Font size for notifications.
sf::Font NotificationWall::font_
Font used for rendering notifications.
NotificationWall::NotificationWall()
Default constructor for the NotificationWall class.
References clearWall, getFont, setFont.
void NotificationWall::clearWall()
Clear all notifications from the wall.
Referenced by NotificationWall.
std::vector< std::shared_ptr< sf::Text > > & NotificationWall::getWall()
Get the vector of shared pointers to sf::Text for notifications. Reference for vector of pointer to text messages in the wall.
Referenced by GameScreen::draw.
void NotificationWall::addToWall(std::string text)
Add a new message to the notification wall. text The text of the message to be added.
References getFont, getFontSize.
unsigned int NotificationWall::getFontSize() const
Get the font size used for rendering notifications. Used font size for Player object.
Referenced by addToWall.
void NotificationWall::setFont(sf::Font font)
Set the font for rendering notifications. font The font to be set.
Referenced by NotificationWall.
sf::Font & NotificationWall::getFont()
Get the font used for rendering notifications. Reference to font of Player object.
Referenced by addToWall, NotificationWall.