GameMenuScreen
std::vector<std::shared_ptr<playerSettings> > GameMenuScreen::playerSettingsList_
Vector of players' settings.
void GameMenuScreen::createPlayerSettingsColumn(int colNum, sf::Vector2f posStart, int yStep)
Creates player settings columns.
colNum The number of columns to create. posStart The starting position of the columns. yStep The step between items in the columns.
GameMenuScreen::GameMenuScreen()
Constructor for the GameMenuScreen class.
References GAME_MENU, gameMenuCreate, ActiveScreen::setScreenType.
void GameMenuScreen::gameMenuCreate()
Function to create the game menu.
References ActiveScreen::addButton, ActiveScreen::getButtons, ActiveScreen::getContextWindow, ActiveScreen::getFont, ContextWindow::GetInstance, ContextWindow::getWindow, RETURN_TO_MAIN_MENU, ActiveScreen::setContextWindow, ActiveScreen::setFont, START_GAME.
Referenced by GameMenuScreen.
ScreenEventType GameMenuScreen::worker()
Worker function for the game menu screen.
The ScreenEventType associated with the user interaction.
References buttonClickHandle, ActiveScreen::buttonSetColors, ActiveScreen::getButtons, ActiveScreen::getContextWindow, IDLE, setOtherButtonsInactive, START_GAME.
void GameMenuScreen::setPlayerSettings(unsigned int index, bool isNone, bool isHuman, int level)
Sets the player settings.
index The index of the player. isNone Flag indicating if the player is set to None. isHuman Flag indicating if the player is human. level The AI level of the player.
Referenced by buttonClickHandle.
void GameMenuScreen::buttonClickHandle(std::shared_ptr< Button > buttonPtr)
Handles button clicks in the game menu.
buttonPtr The shared pointer to the Button clicked.
References PLAYER_1_SET_AI, PLAYER_1_SET_AI_LEVEL_1, PLAYER_1_SET_AI_LEVEL_2, PLAYER_1_SET_AI_LEVEL_3, PLAYER_1_SET_HUMAN, PLAYER_1_SET_NONE, PLAYER_2_SET_AI, PLAYER_2_SET_AI_LEVEL_1, PLAYER_2_SET_AI_LEVEL_2, PLAYER_2_SET_AI_LEVEL_3, PLAYER_2_SET_HUMAN, PLAYER_2_SET_NONE, PLAYER_3_SET_AI, PLAYER_3_SET_AI_LEVEL_1, PLAYER_3_SET_AI_LEVEL_2, PLAYER_3_SET_AI_LEVEL_3, PLAYER_3_SET_HUMAN, PLAYER_3_SET_NONE, PLAYER_4_SET_AI, PLAYER_4_SET_AI_LEVEL_1, PLAYER_4_SET_AI_LEVEL_2, PLAYER_4_SET_AI_LEVEL_3, PLAYER_4_SET_HUMAN, PLAYER_4_SET_NONE, setAILevelColumnVisibility, setDefaultAILevelButtonsFocus, setPlayerSettings.
Referenced by worker.
void GameMenuScreen::setOtherButtonsInactive(std::shared_ptr< Button > buttonPtr)
Sets other buttons inactive when a button is clicked.
buttonPtr The shared pointer to the Button clicked.
References ActiveScreen::getButtons, getPlayerNumFromEventType, isEventTypeAILevel, isEventTypeSetAI.
Referenced by worker.
int GameMenuScreen::getPlayerNumFromEventType(ScreenEventType event)
Gets the player number from the ScreenEventType.
event The ScreenEventType to analyze. The player number.
References PLAYER_1_SET_AI, PLAYER_1_SET_AI_LEVEL_1, PLAYER_1_SET_AI_LEVEL_2, PLAYER_1_SET_AI_LEVEL_3, PLAYER_1_SET_HUMAN, PLAYER_1_SET_NONE, PLAYER_2_SET_AI, PLAYER_2_SET_AI_LEVEL_1, PLAYER_2_SET_AI_LEVEL_2, PLAYER_2_SET_AI_LEVEL_3, PLAYER_2_SET_HUMAN, PLAYER_2_SET_NONE, PLAYER_3_SET_AI, PLAYER_3_SET_AI_LEVEL_1, PLAYER_3_SET_AI_LEVEL_2, PLAYER_3_SET_AI_LEVEL_3, PLAYER_3_SET_HUMAN, PLAYER_3_SET_NONE, PLAYER_4_SET_AI, PLAYER_4_SET_AI_LEVEL_1, PLAYER_4_SET_AI_LEVEL_2, PLAYER_4_SET_AI_LEVEL_3, PLAYER_4_SET_HUMAN, PLAYER_4_SET_NONE.
Referenced by setAILevelColumnVisibility, setOtherButtonsInactive.
void GameMenuScreen::setAILevelColumnVisibility(int playerNum, bool visible)
Sets the AI level column visibility.
playerNum The player number. visible Flag indicating if the column should be visible.
References ActiveScreen::getButtons, getPlayerNumFromEventType, isEventTypeAILevel.
Referenced by buttonClickHandle.
bool GameMenuScreen::isEventTypeAILevel(int playerNum, ScreenEventType event)
Checks if the ScreenEventType is related to AI level.
playerNum The player number. event The ScreenEventType to analyze. True if the event is related to AI level, false otherwise.
References PLAYER_1_SET_AI_LEVEL_1, PLAYER_1_SET_AI_LEVEL_2, PLAYER_1_SET_AI_LEVEL_3, PLAYER_2_SET_AI_LEVEL_1, PLAYER_2_SET_AI_LEVEL_2, PLAYER_2_SET_AI_LEVEL_3, PLAYER_3_SET_AI_LEVEL_1, PLAYER_3_SET_AI_LEVEL_2, PLAYER_3_SET_AI_LEVEL_3, PLAYER_4_SET_AI_LEVEL_1, PLAYER_4_SET_AI_LEVEL_2, PLAYER_4_SET_AI_LEVEL_3.
Referenced by setAILevelColumnVisibility, setOtherButtonsInactive.
bool GameMenuScreen::isEventTypeSetAI(int playerNum, ScreenEventType event)
Checks if the ScreenEventType is related to setting AI.
playerNum The player number. event The ScreenEventType to analyze. True if the event is related to setting AI, false otherwise.
References PLAYER_1_SET_AI, PLAYER_2_SET_AI, PLAYER_3_SET_AI, PLAYER_4_SET_AI.
Referenced by setOtherButtonsInactive.
void GameMenuScreen::setDefaultAILevelButtonsFocus(int playerNum)
Sets the default AI level buttons' focus.
playerNum The player number.
References ActiveScreen::getButtons, PLAYER_1_SET_AI_LEVEL_1, PLAYER_1_SET_AI_LEVEL_2, PLAYER_1_SET_AI_LEVEL_3, PLAYER_2_SET_AI_LEVEL_1, PLAYER_2_SET_AI_LEVEL_2, PLAYER_2_SET_AI_LEVEL_3, PLAYER_3_SET_AI_LEVEL_1, PLAYER_3_SET_AI_LEVEL_2, PLAYER_3_SET_AI_LEVEL_3, PLAYER_4_SET_AI_LEVEL_1, PLAYER_4_SET_AI_LEVEL_2, PLAYER_4_SET_AI_LEVEL_3.
Referenced by buttonClickHandle.
std::vector< std::shared_ptr< playerSettings > > GameMenuScreen::getPlayersSettings() const
Gets the players' settings.
Vector of shared pointers to playerSettings objects.
void GameMenuScreen::draw()
Draws the game menu screen.
References ActiveScreen::getButtons, ActiveScreen::getContextWindow, ActiveScreen::getTexts, ContextWindow::getWindow.