StreetField
std::map<StreetTiers, unsigned int> StreetField::rent_values_
unsigned int StreetField::house_price_
unsigned int StreetField::hotel_price_
unsigned int StreetField::house_number_
bool StreetField::is_hotel_
StreetField::StreetField(const unsigned int id, const FieldType type, const std::string name, const std::string graphic_path, const unsigned int width, const unsigned int height, const float rotation, const sf::Vector2i position, const unsigned int price, const unsigned int house_price, const unsigned int hotel_price, const std::map< StreetTiers, unsigned int > rent_values, const std::vector< unsigned int > group_members, const unsigned int Mortgage)
Constructor for the StreetField class.
id The ID of the field. type The type of the field. name The name of the field. graphic_path The file path to the field's graphic. width The width of the field. height The height of the field. rotation The rotation angle of the field. position The position of the field on the board. price The price of the property. house_price The price of a house. hotel_price The price of a hotel. rent_values The rent values for different tiers. group_members The IDs of the group members (properties in the same group). mortgage The mortgage value of the property.
const std::map< StreetTiers, unsigned int > StreetField::getRentValues()
Gets the rent values for different tiers.
The rent values for different tiers.
Referenced by MonopolyGameEngine::calculateRent, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int StreetField::getHousePrice()
Gets the price of a house.
The price of a house.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::isBuildingLegal, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int StreetField::getHotelPrice()
Gets the price of a hotel.
The price of a hotel.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::isHotelBuildingLegal, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int StreetField::getHouseNumber()
Gets the number of houses on the property.
The number of houses on the property.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::calculateRent, MonopolyGameEngine::colorGroupEmpty, GameScreen::draw, MonopolyGameEngine::isBuildingLegal, MonopolyGameEngine::isDestroyingLegal, MonopolyGameEngine::isHotelBuildingLegal, MonopolyGameEngine::monopolyGameWorker.
bool StreetField::getIsHotel()
Checks if there is a hotel on the property.
True if there is a hotel, false otherwise.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::calculateRent, GameScreen::draw, MonopolyGameEngine::isHotelBuildingLegal, MonopolyGameEngine::isHotelDestroyingLegal, MonopolyGameEngine::monopolyGameWorker.
void StreetField::setHouseNumber(unsigned int new_house_number)
Sets the number of houses on the property.
new_house_number The new number of houses on the property.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, resetDefault.
void StreetField::setIsHotel(bool new_state)
Sets the hotel state on the property.
new_state The new hotel state.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, resetDefault.
void StreetField::resetDefault()
Resets the property to its default state.
References PropertyField::resetOwner, setHouseNumber, setIsHotel, PropertyField::setIsMortgaged.
unsigned int StreetField::calculateRent()
Calculates the rent for the property.
The calculated rent value.