Field
ContextWindow* Field::context_window_
unsigned int Field::id_
FieldType Field::type_
std::string Field::name_
std::string Field::graphic_path_
unsigned int Field::width_
unsigned int Field::height_
float Field::rotation_
sf::Texture Field::texture_
sf::Sprite Field::sprite_
sf::Vector2i Field::position_
sf::Text Field::nameText_
Field::Field(const unsigned int id, const FieldType type, const std::string name, const std::string graphic_path, const unsigned int width, const unsigned int height, const float rotation, const sf::Vector2i position)
Constructor for the Field class.
id The ID of the field. type The type of the field. name The name of the field. graphic_path The file path to the field's graphic. width The width of the field. height The height of the field. rotation The rotation angle of the field. position The position of the field on the board.
ContextWindow * Field::getContextWindow()
Gets the pointer to the context window.
A pointer to the context window.
References ContextWindow::GetInstance.
unsigned int Field::getId()
Gets the ID of the field.
The ID of the field.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, PropertyField::createFlagSprite, Board::getFieldById.
FieldType Field::getType()
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, Board::Board, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::calculateRent, GameScreen::draw, Withdraw::makeWithdraw, MonopolyGameEngine::monopolyGameWorker, MonopolyGameEngine::performAuction, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
const std::string Field::getName()
Gets the name of the field.
The name of the field.
Referenced by MonopolyGameEngine::aiBuildingsMangingWorker, MonopolyGameEngine::buildingsManagingWorker, MonopolyGameEngine::createTextPlayersInfo, MonopolyGameEngine::monopolyGameWorker, Withdraw::setDecisionScreenVisible, Withdraw::showProperty, MonopolyGameEngine::showPropertyData, MonopolyGameEngine::updateTextPlayersInfo.
const std::string Field::getGraphicPath()
Gets the file path to the field's graphic.
The file path to the field's graphic.
Referenced by Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int Field::getWidth()
Gets the width of the field.
The width of the field.
Referenced by PropertyField::createFlagSprite, MonopolyGameEngine::createPlayers, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int Field::getHeight()
Gets the height of the field.
The height of the field.
Referenced by PropertyField::createFlagSprite, MonopolyGameEngine::createPlayers, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
float Field::getRotation()
Gets the rotation angle of the field.
The rotation angle of the field.
Referenced by PropertyField::createFlagSprite, GameScreen::draw, MonopolyGameEngine::getHotelSprite, MonopolyGameEngine::getHouseSprite.
const sf::Sprite & Field::getSprite()
Gets the sprite representing the field.
The sprite representing the field.
Referenced by GameScreen::draw.
const sf::Texture & Field::getTexture()
Gets the texture of the field.
The texture of the field.
const sf::Vector2i & Field::getPosition()
Gets the position of the field on the board.
The position of the field on the board.
Referenced by PropertyField::createFlagSprite, MonopolyGameEngine::getHotelSprite, MonopolyGameEngine::getHouseSprite.
const sf::Text & Field::getNameText()
Gets the text representing the name of the field.
The text representing the name of the field.
Referenced by GameScreen::draw.
void Field::createSprite()
Creates the sprite for the field.
Referenced by Board::Board.
void Field::setHeight(unsigned int new_height)
Sets the height of the field.
new_height The new height of the field.
References ContextWindow::window_.
void Field::setWidth(unsigned int new_width)
Sets the width of the field.
new_width The new width of the field.
References ContextWindow::window_.
void Field::setRotation(float new_rotation)
Sets the rotation angle of the field.
new_rotation The new rotation angle of the field.
void Field::setPosition(sf::Vector2i pos)
Sets the position of the field on the board.
pos The new position of the field.