StationField
std::map<StationTiers, unsigned int> StationField::rent_values_
StationField::StationField(const unsigned int id, const FieldType type, const std::string name, const std::string graphic_path, const unsigned int width, const unsigned int height, const float rotation, const sf::Vector2i position, const unsigned int price, const std::map< StationTiers, unsigned int > rent_values, const std::vector< unsigned int > group_members, const unsigned int Mortgage)
Constructor for the StationField class.
id The ID of the field. type The type of the field. name The name of the field. graphic_path The file path to the field's graphic. width The width of the field. height The height of the field. rotation The rotation angle of the field. position The position of the field on the board. price The price of the property. rent_values The rent values for different tiers. group_members The IDs of the group members (properties in the same group). mortgage The mortgage value of the property.
const std::map< StationTiers, unsigned int > StationField::getRentValues()
Gets the rent values for different tiers.
The rent values for different tiers.
Referenced by MonopolyGameEngine::calculateRent, Withdraw::showProperty, MonopolyGameEngine::showPropertyData.
unsigned int StationField::calculateRent()
Calculates the rent for the property.
The calculated rent value.