GameEngine
ContextWindow* GameEngine::context_window_
Pointer to the context window used for rendering graphics.
std::unique_ptr<ActiveScreen> GameEngine::active_screen_
Unique pointer to the active screen managing different purpose screens.
double GameEngine::frame_rate_hz_
Frame rate in Hertz (frames per second).
sf::Time GameEngine::frame_rate_delay_ms_
Time delay for achieving the specified frame rate.
unsigned int GameEngine::window_width_
Width of the game window in pixels.
unsigned int GameEngine::window_height_
Height of the game window in pixels.
std::vector<std::shared_ptr<Player> > GameEngine::players_
Vector of shared pointers to Player objects representing game players.
GameEngine::GameEngine(double frame_rate_hz, uint window_width, uint window_height)
Constructor for the GameEngine class.
frame_rate_hz Desired frame rate in Hertz (frames per second). window_width Width of the game window in pixels. window_height Height of the game window in pixels.
References getContextWindow, ContextWindow::GetInstance, ContextWindow::getView, ContextWindow::getWindow.
GameEngine::GameEngine(double frame_rate_hz)
Additional constructor for the GameEngine class. Used only to train AI players.
frame_rate_hz Desired frame rate in Hertz (frames per second).
References getContextWindow, ContextWindow::GetInstance, ContextWindow::getView, ContextWindow::getWindow.
void GameEngine::clear()
Clears content on the displayed window.
References getContextWindow, ContextWindow::getWindow.
Referenced by worker.
void GameEngine::display()
Displays the content of the context window.
References ContextWindow::display, getContextWindow.
Referenced by worker.
void GameEngine::pollForEvents(sf::Event &event)
Polls for events such as mouse and keyboard interactions.
event Reference to an sf::Event object to store the polled event.
References getContextWindow, ContextWindow::getWindow.
Referenced by worker.
std::vector< std::shared_ptr< Player > > GameEngine::worker(std::vector< std::shared_ptr< Player >> &players_vec)
Worker function for processing player-related tasks.
players_vec Vector of shared pointers to Player objects representing game players. Vector of shared pointers to Player objects after processing.
References clear, display, EXIT, GAME_ENDED, getContextWindow, IDLE, ann::neuralnet::import_fromfile, playerSettings::isHuman, playerSettings::isNone, playerSettings::level, PLAY, pollForEvents, RETURN_TO_MAIN_MENU, Player::setAiLevel, Player::setIsAi, START_GAME.
unsigned int GameEngine::getwindow_width() const
Gets the width of the game window.
Width of the game window in pixels.
unsigned int GameEngine::getwindow_height() const
Gets the height of the game window.
Height of the game window in pixels.
ContextWindow * GameEngine::getContextWindow()
Gets the pointer to the context window.
Pointer to the context window used for rendering graphics.
Referenced by clear, display, GameEngine, pollForEvents, worker.